# Inference pipeline

At this point, you should have the following files for the models trained on data from BWC batches 160 to 200:

1. `models/stage1_best_model.joblib`
2. `models/stage2_best_model.joblib`

You should also have unseen gradesheet data (in .xlsx) that you want to run inference on in `data/unseen` folder.

To run evaluation against known ground truth labels, ground truth data (in .xlsx) must be in `data/labels` folder. 

This notebook is currently running inference on data from BWC batches 201 and onwards. Predictions will be saved to `predictions` folder.

## Imports, constants

In [1]:
import pandas as pd
import joblib
from pathlib import Path

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
)

MODULE_1 = [
    "GH 1",
    "GH 2",
    "GH 3",
    "GH 4",
    "GH 5",
    "GH 6",
    "GH 7",
    "GH 8",
    "GH 9",
    "GH 10",
    "GH 11",
    "GH 12",
    "GH 13",
    "GH 14",
    "GH 15",
    "GH 17",
    "GH 19",
    "GH 21",
    "GH 22",
]

MODULE_2 = [
    "GH 24",
    "GH 25",
    "GH 27",
    "GH 28",
    "GH 29",
    "GH 30",
    "GH 31",
    "GH 32",
    "GH 33",
    "GH 34",
    "GHT",
]

MODULE_3 = ["IF 1", "IF 2", "IF 3", "IF 4", "IF 5", "IF 6", "IFT"]

MODULE_6 = ["AN 1", "AN 2", "AN 3", "AN 4", "AN 5", "AN 6", "AN 7"]

LESSONS_TO_KEEP = MODULE_1 + MODULE_2 + MODULE_3

## Prepare data for inference

### Read raw unseen data

In [2]:
# Read raw unseen data
dfs = []
for file in Path("data/unseen").glob("*.xlsx"):
    df = pd.read_excel(file)
    dfs.append(df)
df = pd.concat(dfs, ignore_index=True)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 143163 entries, 0 to 143162
Data columns (total 73 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   STUDENT_ID                      143163 non-null  str
 1   STUDENT_FIRST_NAME              143163 non-null  str
 2   STUDENT_LAST_NAME               143163 non-null  str
 3   STUDENT_DISPLAY_NAME            143163 non-null  str
 4   STUDENT_TITLE                   143163 non-null  str
 5   STUDENT_RANK                    0 non-null       float64
 6   STUDENT_RANK_ABBREV             0 non-null       float64
 7   COURSE                          86974 non-null   str
 8   CLASS_TEMP_DS_ID                86974 non-null   str
 9   CLASS                           143163 non-null  str
 10  CLASS_DS_ID                     86974 non-null   str
 11  COURSE_START_DATE               68665 non-null   datetime64[us]
 12  COURSE_END_DATE                 68665 non-null   datetime64[us]
 13  COURSE_ACTUAL_START_DATE        68665 non-null   datetime64[us]
 14  COURSE_ACTUAL_END_DATE          653 non-null     float64
 15  MODULE_NAME                     87180 non-null   str
 16  MODULE_DS_ID                    86974 non-null   str
 17  MODULE_TEMP_NAME                86974 non-null   str
 18  MODULE_TEMP_DS_ID               86974 non-null   str
 19  LESSON_START_DATE               133664 non-null  datetime64[us]
 20  LESSON_END_DATE                 133664 non-null  datetime64[us]
 21  LESSON_ACTUAL_START_DATE        143163 non-null  datetime64[us]
 22  LESSON_ACTUAL_END_DATE          131368 non-null  datetime64[us]
 23  LESSON_NUMBER                   143163 non-null  str
 24  LESSON_DS_ID                    142867 non-null  str
 25  LESSON_DESCRIPTION              0 non-null       float64
 26  PLAN_DISPLAY_ID                 143163 non-null  int64
 27  LESSON_TEMPLATE_COMMENTS        22264 non-null   object
 28  LESSON_TEMP_NAME                143163 non-null  str
 29  LESSON_TEMP_DS_ID               142867 non-null  str
 30  PLAN_TEMPLATE_DURATION          143163 non-null  float64
 31  PLAN_TEMPLATE_DURATION_TYPE     143163 non-null  str
 32  PLAN_TEMPLATE_DS_ID             142867 non-null  str
 33  PLAN_TYPE_ID                    143163 non-null  str
 34  SUB_PLAN_TYPE_ID                143163 non-null  str
 35  PLAN_CATEGORY_ID                25491 non-null   str
 36  ABORT_REASON                    99 non-null      str
 37  ABORT_CODE                      99 non-null      str
 38  TAKE_OFF_TIME                   89322 non-null   object
 39  LANDING_TIME                    89322 non-null   object
 40  ACTUAL_FLIGHT_HOURS             99460 non-null   float64
 41  DUTY_STATUS_DESCRIPTION         130610 non-null  str
 42  WEATHER_CODE_DESCRIPTION        130592 non-null  str
 43  SOLO_SHEET_MAN_NOT              0 non-null       float64
 44  INSTRUCTOR_ID                   134602 non-null  str
 45  INSTRUCTOR_FIRST_NAME           134602 non-null  str
 46  INSTRUCTOR_LAST_NAME            134602 non-null  str
 47  INSTRUCTOR_DISPLAY_NAME         134602 non-null  str
 48  INSTRUCTOR_TITLE                134602 non-null  str
 49  INSTRUCTOR_RANK                 4236 non-null    str
 50  INSTRUCTOR_RANK_ABBREV          4236 non-null    str
 51  AVERAGE_SCORE                   132010 non-null  float64
 52  ADJUSTED_SCORE                  6805 non-null    float64
 53  EMP_EVAL_COMMENTS               130641 non-null  str
 54  EMP_EVAL_SCORE                  131549 non-null  float64
 55  EMP_EVAL_RANKING                0 non-null       float64
 56  EVALUATOR_ACKNOWLEDGED          131718 non-null  float64
 57  EVALUATOR_ACKNOWLEDGED_DATE     108219 non-null  datetime64[us]
 58  EVAL_ACK_BY_EMPLOYEE_DS_ID      130944 non-null  str
 59  EMPLOYEE_ACKNOWLEDGED           131718 non-null  float64
 60  EMPLOYEE_ACKNOWLEDGED_DATE      43387 non-null   object
 61  EMP_ACK_BY_EMPLOYEE_DS_ID       45282 non-null   str
 62  OBJECTIVE_ID                    142822 non-null  str
 63  OBJECTIVE_DESCRIPTION           142822 non-null  str
 64  OBJECTIVE_RAW_SCORE             131174 non-null  float64
 65  OBJECTIVE_WEIGHTED_SCORE        131174 non-null  float64
 66  OBJECTIVE_SCORE_WEIGHT          131708 non-null  float64
 67  OBJECTIVE_CRITICAL              131708 non-null  float64
 68  OBJECTIVE_ACCEPTABLE_SCORE      131708 non-null  float64
 69  OBJECTIVE_EXPECTED_SCORE        131708 non-null  float64
 70  OBJECTIVE_ACCEPTABLE_SCORE_DSC  131708 non-null  str
 71  OBJECTIVE_EXPECTED_SCORE_DSC    131708 non-null  str
 72  OBJECTIVE_COMMENTS              38682 non-null   str
dtypes: datetime64[us](8), float64(19), int64(1), object(4), str(41)
memory usage: 150.6+ MB

### Clean data

In [3]:
# Drop duplicate rows
df = df.drop_duplicates()

# Drop rows with null values in key columns
df = df.dropna(subset=["STUDENT_ID", "LESSON_NUMBER", "EMP_EVAL_SCORE"])

# Keep only the relevant lesson numbers (modules 1 to 3)
# This step also removes rows with suffixes.
df = df[df["LESSON_NUMBER"].isin(LESSONS_TO_KEEP)]

# Drop rows with NG in EMP_EVAL_COMMENTS
df = df[
    ~df["EMP_EVAL_COMMENTS"]
    .astype("string")
    .str.contains(r"\bNG\b", case=False, na=False)
]

# Drop rows with DNCO
df = df[
    ~(
        df["DUTY_STATUS_DESCRIPTION"].astype("string").eq("DNCO")
        | df["EMP_EVAL_COMMENTS"]
        .astype("string")
        .str.contains(r"\bDNCO\b", case=False, na=False)
    )
]

# Keep only the first row for a given STUDENT_ID and LESSON_NUMBER
df = df.drop_duplicates(subset=["STUDENT_ID", "LESSON_NUMBER", "LESSON_ACTUAL_START_DATE"])

# Reorder columns for readability
first_cols = [
    "STUDENT_ID",
    "LESSON_NUMBER",
    "LESSON_ACTUAL_START_DATE",
    "LESSON_ACTUAL_END_DATE",
    "EMP_EVAL_SCORE",
    "EMP_EVAL_COMMENTS",
    "DUTY_STATUS_DESCRIPTION",
    "ADJUSTED_SCORE",
    "AVERAGE_SCORE",
    "OBJECTIVE_DESCRIPTION",
    "OBJECTIVE_RAW_SCORE",
    "OBJECTIVE_SCORE_WEIGHT",
    "OBJECTIVE_WEIGHTED_SCORE",
    "OBJECTIVE_CRITICAL",
    "OBJECTIVE_ACCEPTABLE_SCORE",
    "OBJECTIVE_ACCEPTABLE_SCORE_DSC",
]
remaining_cols = [col for col in df.columns if col not in first_cols]
df = df[first_cols + remaining_cols]

# Sort by STUDENT_ID
df = df.sort_values(by=["STUDENT_ID", "LESSON_ACTUAL_START_DATE"]).reset_index(drop=True)

### Pivot

In [4]:
# Pivot
wide = (
    df.pivot_table(
        index="STUDENT_ID",
        columns="LESSON_NUMBER",
        values="EMP_EVAL_SCORE",
        aggfunc="first",
    )
    .reset_index()
)

# Reorder columns
wide = wide[["STUDENT_ID"] + LESSONS_TO_KEEP]
wide.columns.name = None
wide

,STUDENT_ID,GH 1,GH 2,GH 3,GH 4,GH 5,GH 6,GH 7,GH 8,GH 9,...,GH 33,GH 34,GHT,IF 1,IF 2,IF 3,IF 4,IF 5,IF 6,IFT
0,201EEZ,5.179442,5.267281,5.234087,4.355000,4.045916,4.367075,4.779347,3.446281,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201HLEE,4.624989,4.917051,4.332565,4.444498,4.816778,3.785408,4.155844,4.118668,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,201HONT,5.113508,4.917051,4.133894,4.671514,4.773037,4.735986,4.372067,3.616723,NaN,...,NaN,4.101320,4.173327,5.027020,4.245510,4.539404,4.406282,3.777039,4.195178,4.557287
3,201KHOOC,5.301836,4.977205,4.503209,4.634096,4.935050,4.214286,4.815559,4.484804,NaN,...,NaN,4.357262,4.421186,5.377912,5.277256,4.344802,4.386612,NaN,4.888308,4.204591
4,201KOHJ,5.113508,4.917051,4.266631,4.425050,4.351428,4.299694,3.487584,3.593985,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,207LUH,5.420786,4.794602,4.912946,4.866944,4.574162,4.505554,4.466744,4.434889,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,207SEAHI,5.113508,5.342156,4.528630,5.110352,5.084466,4.620851,4.466744,4.513689,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,207SOHY,4.871720,4.977205,4.657893,4.957826,4.290271,4.736512,4.926931,4.198177,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,207TANK,4.994169,5.210692,4.266631,4.910062,4.727366,4.335183,4.428571,4.173113,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,207TIONGT,4.914529,5.036647,4.144819,4.364604,4.083585,4.427559,4.662338,4.263777,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Run inference

In [5]:
# Load trained model
stage1_best_model = joblib.load("models/stage1_best_model.joblib")
stage2_best_model = joblib.load("models/stage2_best_model.joblib")

### Stage 1: Predict BWC pass or fail

In [6]:
# Keep only the feature columns
X1 = wide.drop(columns="STUDENT_ID")

# Get predictions and associated probability
y_pred1 = stage1_best_model.predict(X1)
y_score1 = stage1_best_model.predict_proba(X1)[:, 1]

# Append back to wide span table
wide["pred_bwc"] = y_pred1
wide["prob_bwc"] = y_score1
assert wide["pred_bwc"].isnull().sum() == 0
wide

,STUDENT_ID,GH 1,GH 2,GH 3,GH 4,GH 5,GH 6,GH 7,GH 8,GH 9,...,GHT,IF 1,IF 2,IF 3,IF 4,IF 5,IF 6,IFT,pred_bwc,prob_bwc
0,201EEZ,5.179442,5.267281,5.234087,4.355000,4.045916,4.367075,4.779347,3.446281,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.118992
1,201HLEE,4.624989,4.917051,4.332565,4.444498,4.816778,3.785408,4.155844,4.118668,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.065594
2,201HONT,5.113508,4.917051,4.133894,4.671514,4.773037,4.735986,4.372067,3.616723,NaN,...,4.173327,5.027020,4.245510,4.539404,4.406282,3.777039,4.195178,4.557287,1.0,0.881256
3,201KHOOC,5.301836,4.977205,4.503209,4.634096,4.935050,4.214286,4.815559,4.484804,NaN,...,4.421186,5.377912,5.277256,4.344802,4.386612,NaN,4.888308,4.204591,1.0,0.902146
4,201KOHJ,5.113508,4.917051,4.266631,4.425050,4.351428,4.299694,3.487584,3.593985,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.014283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,207LUH,5.420786,4.794602,4.912946,4.866944,4.574162,4.505554,4.466744,4.434889,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.078722
95,207SEAHI,5.113508,5.342156,4.528630,5.110352,5.084466,4.620851,4.466744,4.513689,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.026853
96,207SOHY,4.871720,4.977205,4.657893,4.957826,4.290271,4.736512,4.926931,4.198177,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.050677
97,207TANK,4.994169,5.210692,4.266631,4.910062,4.727366,4.335183,4.428571,4.173113,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.027626
98,207TIONGT,4.914529,5.036647,4.144819,4.364604,4.083585,4.427559,4.662338,4.263777,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.078946

### Stage 2: Among predicted BWC passes, predict fighter or not

In [7]:
# Keep only predicted passes
passes = wide[wide["pred_bwc"] == 1].drop(columns=["pred_bwc", "prob_bwc"])

# Keep only the feature columns
X2 = passes.drop(columns=["STUDENT_ID"])

# Get predictions and associated probability
y_pred2 = stage2_best_model.predict(X2)
y_score2 = stage2_best_model.predict_proba(X2)[:, 1]

# Append back to wide span table
passes["pred_fighter"] = y_pred2
passes["prob_fighter"] = y_score2
assert passes["pred_fighter"].isnull().sum() == 0
passes

,STUDENT_ID,GH 1,GH 2,GH 3,GH 4,GH 5,GH 6,GH 7,GH 8,GH 9,...,GHT,IF 1,IF 2,IF 3,IF 4,IF 5,IF 6,IFT,pred_fighter,prob_fighter
2,201HONT,5.113508,4.917051,4.133894,4.671514,4.773037,4.735986,4.372067,3.616723,NaN,...,4.173327,5.027020,4.245510,4.539404,4.406282,3.777039,4.195178,4.557287,0.0,0.365022
3,201KHOOC,5.301836,4.977205,4.503209,4.634096,4.935050,4.214286,4.815559,4.484804,NaN,...,4.421186,5.377912,5.277256,4.344802,4.386612,NaN,4.888308,4.204591,1.0,0.523451
5,201KOHZ,5.813411,6.180373,5.756446,4.930210,4.751955,4.814494,5.047512,5.502013,NaN,...,3.965473,5.071061,4.491836,4.585104,3.962011,4.507744,3.785039,4.760613,1.0,0.699344
6,201KSARAN,5.301836,4.977205,4.398210,4.249666,4.473469,4.039001,4.233766,4.197280,NaN,...,3.926079,4.270524,4.368571,4.306142,4.388513,3.631730,3.957875,4.258857,0.0,0.234078
7,201LEEJ,5.116952,4.977205,5.101195,5.016398,5.315733,4.388821,4.257563,4.376099,NaN,...,4.702097,4.628361,4.860992,4.438608,4.468097,4.295469,3.913083,4.211606,0.0,0.467614
8,201LIMK,6.084082,5.653140,5.051111,4.808638,4.633721,4.890357,4.692850,4.456488,NaN,...,4.789537,4.315432,4.409637,4.278003,3.924180,NaN,NaN,NaN,0.0,0.470441
9,201ONGE,5.116952,4.972374,4.398210,4.813387,4.713961,4.731633,4.488572,4.641768,NaN,...,4.342767,4.225564,3.667171,4.657209,4.244153,4.449425,4.486976,4.578947,1.0,0.536148
10,201PANGM,5.398251,5.267281,4.975985,5.001205,4.792674,5.180113,4.896214,5.325728,NaN,...,4.036151,4.672861,4.601960,4.383548,4.428227,4.260308,4.519801,4.568555,1.0,0.539588
11,201TANGK,4.670175,4.574422,4.173120,4.784895,5.006211,4.334886,4.135399,4.117753,NaN,...,4.286667,4.583810,5.163993,4.422381,4.468097,3.481036,4.163149,4.385917,0.0,0.440448
12,202ANGK,5.286686,4.908005,4.430533,4.516597,5.039315,4.489297,4.477631,4.909192,NaN,...,4.226671,4.806054,4.656508,4.422381,4.519171,4.054513,4.118079,4.740115,0.0,0.459371
14,202CHUAL,5.054227,4.475998,4.912946,5.281316,4.857143,4.734984,4.652154,4.563636,NaN,...,4.576582,5.202875,4.904195,5.217324,4.588651,3.722596,4.160746,4.406520,1.0,0.651500
15,202CHUNGS,6.099165,6.322603,4.849616,4.912521,5.957226,5.331703,5.495941,NaN,NaN,...,5.266272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.816490
16,202HOJ,4.994169,5.267281,4.849297,4.872212,4.965671,4.171429,4.300551,4.711681,NaN,...,4.411200,4.717309,4.406474,4.543650,4.916574,3.943482,4.799446,NaN,0.0,0.468523
17,202LEEL,5.714286,5.432768,5.163366,4.828686,4.703705,4.385004,4.000000,4.513689,NaN,...,4.580480,4.806054,5.028345,5.145454,5.212592,4.929298,4.077359,4.268215,1.0,0.522704
18,202LEEY,5.113508,5.342156,4.332565,4.261819,4.318105,4.652154,4.311373,4.165772,NaN,...,4.180535,4.494555,4.389263,4.855292,4.309555,4.164966,4.494331,4.254153,0.0,0.461219
19,202LOHX,5.506706,5.267281,4.711017,5.110352,4.928649,5.237995,4.814494,4.700950,NaN,...,4.037267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.722358
21,202NGJ,5.559767,6.099310,4.912946,4.964333,4.812421,4.466270,4.967122,4.950954,NaN,...,4.523809,5.811928,4.904195,5.380489,4.863131,4.974786,NaN,4.528181,1.0,0.787746
22,202PHUAC,5.566512,5.539527,4.332565,5.522015,5.148779,4.559006,5.082071,4.530098,NaN,...,4.479075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.786162
23,202POHK,5.559767,5.432768,4.973761,4.748741,4.816778,4.530023,4.451689,4.740260,NaN,...,4.033371,4.494555,4.656508,4.696652,4.320504,3.786706,4.077359,4.610088,0.0,0.459833
24,202SOOE,5.229738,5.530162,4.266631,5.210907,4.773037,4.659431,4.371951,4.149956,NaN,...,4.614127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.699920
25,202THAMY,5.188766,5.098765,4.657893,4.913397,4.376093,4.000000,4.697985,4.478764,NaN,...,4.175300,4.628361,4.245510,4.578585,4.468097,4.164966,3.332755,4.380395,0.0,0.433368
26,202TOKJ,5.342857,5.153390,4.785998,4.915474,5.215955,4.717309,4.386580,4.683424,NaN,...,4.271530,4.982930,5.568685,4.696652,5.648159,4.383665,4.478392,4.163149,1.0,0.647568
27,202WONGS,6.204082,5.929952,5.151319,5.918257,4.900162,4.995321,4.997663,4.909413,NaN,...,3.962486,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.774265
28,202YUQ,5.054227,4.856183,5.038735,5.333555,5.274878,4.614035,4.777773,4.713634,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.779840
29,203GOHJ,5.286686,5.486504,4.428571,5.101343,4.493702,4.931595,4.814494,5.036286,NaN,...,4.243850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.697104
32,203KTENG,5.956735,5.267281,4.720341,4.908704,5.006211,4.350236,4.334886,4.035820,4.362249,...,3.961285,5.027020,4.450726,5.136263,4.972116,4.671242,4.355591,4.380395,0.0,0.392214
34,203LEED,4.989390,4.977205,4.265082,4.552180,4.751955,1.642857,5.273129,4.872727,NaN,...,4.208504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.629700
35,203LIAUD,5.229738,5.267281,4.784481,4.431277,4.551069,4.311373,4.466270,4.699192,4.955084,...,4.078106,4.180553,4.257563,4.895170,4.588651,4.531988,4.355591,3.876387,0.0,0.467094
36,203LOHJ,6.178814,5.643433,5.475219,5.083488,4.935671,4.530023,4.928752,4.645015,NaN,...,3.762036,4.360289,4.615306,4.609127,4.052018,4.248193,4.755102,4.406520,0.0,0.482921
37,203NGK,5.631020,5.453416,4.655977,5.025485,4.614198,4.543613,4.556848,4.415649,NaN,...,4.000000,4.494555,4.738980,4.815502,4.192296,4.231255,5.559832,4.177566,0.0,0.441863
39,203TANZ,5.384401,5.160787,4.848351,4.463565,4.799503,4.825130,4.667440,3.511794,NaN,...,4.068820,4.761707,4.780250,4.804609,4.120075,4.051228,4.946934,3.958517,0.0,0.379446
40,203THONGW,4.515795,5.486504,4.526576,5.289312,4.816778,4.569683,4.724702,4.673539,NaN,...,4.358580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.791595
42,203YYEO,5.956268,6.046712,5.088921,5.198722,4.693878,4.997663,5.196784,5.552825,NaN,...,4.892115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.864410
43,204BOEYC,5.581224,5.486504,4.849616,5.101343,5.611046,4.851935,4.530023,5.036286,NaN,...,4.609744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.843095
44,204CHUAH,5.612050,5.643433,4.528630,4.833542,4.414733,4.555892,4.900000,5.394239,NaN,...,4.223913,4.982930,4.904195,5.145454,4.917027,4.520642,4.211606,3.954017,1.0,0.618136
45,204CKOH,5.053602,4.710203,4.266631,4.466277,4.423997,4.287156,4.774218,4.164432,NaN,...,4.411200,4.938787,4.409637,4.114151,4.270312,3.857224,3.512027,3.801960,0.0,0.314927
46,204LIEWJ,5.775510,5.901316,5.429148,4.872212,4.627655,5.425500,5.317524,4.525890,NaN,...,4.950853,4.285426,4.368571,4.306142,4.000000,3.832002,4.385917,4.547623,1.0,0.589365
47,204NGZ,5.172012,5.378319,4.657893,4.649554,4.683735,4.287156,4.652154,4.662815,NaN,...,4.759961,4.894594,4.731397,4.657209,4.883696,4.781905,4.451751,4.041763,1.0,0.609467
48,204ONGH,5.054227,5.267281,4.912946,4.332445,4.674683,4.223516,4.389085,4.957063,NaN,...,4.075668,4.225564,4.558849,4.578585,4.270312,4.053456,4.561446,3.883702,0.0,0.440350
49,204ONGJ,4.809329,5.210692,5.263708,5.333149,4.900162,5.107219,5.545709,5.198877,NaN,...,3.770954,4.405096,4.532970,4.461302,4.000000,4.101014,4.077359,4.211606,1.0,0.512174
51,204SEEY,5.229738,5.036647,4.657893,4.347627,4.288330,4.939008,4.544351,4.864666,NaN,...,4.342767,4.225564,4.129281,5.015325,4.829802,4.383665,3.742980,3.959265,0.0,0.421307
53,204TANX,5.286686,4.856183,4.398210,4.387152,4.476191,4.427521,4.584415,4.082719,NaN,...,4.035734,4.521825,4.945556,4.975186,4.270312,4.586422,4.120182,3.520627,0.0,0.385723
54,204TEOJ,6.568645,6.596805,5.756446,5.546334,5.194163,5.094694,5.058769,NaN,NaN,...,4.505771,5.290495,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.866148
57,205CHEONGG,5.188766,5.251473,4.200407,4.444498,4.122449,4.768909,4.779221,4.478764,NaN,...,4.381477,4.583810,4.615306,4.733822,4.515547,3.832002,4.623583,3.959265,1.0,0.551138
59,205HUANGK,2.071429,4.612637,4.697959,4.653503,4.408425,4.427559,4.699406,4.788603,NaN,...,3.752381,4.761707,4.204535,NaN,NaN,NaN,NaN,NaN,0.0,0.356134
64,205LUIL,4.924317,5.160787,4.917947,4.770194,5.124462,5.023953,4.858888,4.876799,NaN,...,4.426746,4.628361,4.780250,4.617854,4.428227,4.102874,4.155668,4.000000,0.0,0.492902
65,205TANW,5.420786,5.793943,NaN,5.150677,5.110823,4.704246,4.854251,5.498039,NaN,...,4.246663,4.449851,4.615306,4.037963,3.627172,3.832002,NaN,4.258857,0.0,0.469649
66,205TJOENGY,5.116952,4.908005,4.986270,4.587764,4.747938,NaN,4.244785,4.078449,NaN,...,4.217200,4.449851,4.862857,4.736181,4.388513,3.938054,4.000000,3.497153,0.0,0.402166
72,206CHOONGD,5.452867,5.643433,5.709879,5.730157,5.045993,5.577452,5.542857,NaN,NaN,...,4.485131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.903805
83,206YEWP,5.909427,6.030530,5.409156,5.210907,4.412720,4.582246,4.814891,4.349187,NaN,...,3.931123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.713748

### Final output

In [8]:
predictions = pd.merge(
    wide[["STUDENT_ID", "pred_bwc", "prob_bwc"]],
    passes[["STUDENT_ID", "pred_fighter", "prob_fighter"]],
    on="STUDENT_ID",
    how="left",
)
predictions = predictions.fillna(0.0)

In [9]:
predictions.head(20)

   STUDENT_ID  pred_bwc  prob_bwc  pred_fighter  prob_fighter
0      201EEZ       0.0  0.118992           0.0      0.000000
1     201HLEE       0.0  0.065594           0.0      0.000000
2     201HONT       1.0  0.881256           0.0      0.365022
3    201KHOOC       1.0  0.902146           1.0      0.523451
4     201KOHJ       0.0  0.014283           0.0      0.000000
5     201KOHZ       1.0  0.741961           1.0      0.699344
6   201KSARAN       1.0  0.938351           0.0      0.234078
7     201LEEJ       1.0  0.939199           0.0      0.467614
8     201LIMK       1.0  0.752536           0.0      0.470441
9     201ONGE       1.0  0.933237           1.0      0.536148
10   201PANGM       1.0  0.950481           1.0      0.539588
11   201TANGK       1.0  0.925688           0.0      0.440448
12    202ANGK       1.0  0.847806           0.0      0.459371
13   202CHOWY       0.0  0.075443           0.0      0.000000
14   202CHUAL       1.0  0.924920           1.0      0.651500
15  202CHUNGS       1.0  0.581293           1.0      0.816490
16     202HOJ       1.0  0.758449           0.0      0.468523
17    202LEEL       1.0  0.949490           1.0      0.522704
18    202LEEY       1.0  0.965429           0.0      0.461219
19    202LOHX       1.0  0.667165           1.0      0.722358

In [10]:
predictions.tail(20)

   STUDENT_ID  pred_bwc  prob_bwc  pred_fighter  prob_fighter
79    206TANA       0.0  0.034931           0.0      0.000000
80    206TANN       0.0  0.195341           0.0      0.000000
81    206TANS       0.0  0.139525           0.0      0.000000
82    206YEOG       0.0  0.458989           0.0      0.000000
83    206YEWP       1.0  0.525294           1.0      0.713748
84    207ANGD       0.0  0.027212           0.0      0.000000
85  207HAZWAN       0.0  0.094309           0.0      0.000000
86   207JLIEW       0.0  0.208354           0.0      0.000000
87   207KANGB       0.0  0.046364           0.0      0.000000
88    207KOHQ       0.0  0.112053           0.0      0.000000
89  207KUMARS       0.0  0.110076           0.0      0.000000
90    207LEET       0.0  0.035617           0.0      0.000000
91    207LIMH       0.0  0.021871           0.0      0.000000
92    207LIMJ       0.0  0.345399           0.0      0.000000
93     207LIY       0.0  0.291559           0.0      0.000000
94     207LUH       0.0  0.078722           0.0      0.000000
95   207SEAHI       0.0  0.026853           0.0      0.000000
96    207SOHY       0.0  0.050677           0.0      0.000000
97    207TANK       0.0  0.027626           0.0      0.000000
98  207TIONGT       0.0  0.078946           0.0      0.000000

In [11]:
predictions.to_csv("predictions/201-207_predictions.csv", index=False)

## Evaluate against known ground truth

Ground truth is taken from `data/labels/BWC201t207_Status_as_of_end_Feb2026.xlsx`, as sent by Tommy to Melody on Defence mail on 13 March 2026.

### Get ground truth

In [12]:
# Load ground truth
ground_truth = pd.read_excel("data/labels/BWC201t207_Status_as_of_end_Feb2026.xlsx")
ground_truth = ground_truth.rename(columns={"STUDENT_ID_ORIG": "STUDENT_ID"})

# Create target columns
ground_truth["target_bwc"] = pd.NA
ground_truth.loc[ground_truth["BWC_Status"] == "Fail", "target_bwc"] = 0.0
ground_truth.loc[
    ground_truth["BWC_Status"].isin(["Pass", "DNF(SUPT)"]), "target_bwc"
] = 1.0
ground_truth["target_bwc"].astype("Float64")

ground_truth["target_fighter"] = pd.NA
ground_truth.loc[
    ((ground_truth["target_bwc"].notna()) & (ground_truth["Stream_Group"] != "Fighter")),
    "target_fighter",
] = 0.0
ground_truth.loc[
    ((ground_truth["target_bwc"] == 1.0) & (ground_truth["Stream_Group"] == "Fighter")),
    "target_fighter",
] = 1.0
ground_truth["target_bwc"].astype("Float64")

if len(ground_truth) != len(predictions):
    print(set(ground_truth["STUDENT_ID"].unique()) - set(predictions["STUDENT_ID"].unique()))
    print(set(predictions["STUDENT_ID"].unique()) - set(ground_truth["STUDENT_ID"].unique()))

{'202LIMN'}
set()

In [13]:
final = pd.merge(ground_truth, predictions, on="STUDENT_ID", how="left")

# Drop rows where target_BWC is nan, i.e. Ongoing, DNF due to med, disciplinary, etc.
final = final.dropna(subset="target_bwc").reset_index(drop=True)

# Enforce datatype
for col in ["target_bwc", "target_fighter", "pred_bwc", "pred_fighter", "prob_bwc", "prob_fighter"]:
    final[col] = final[col].astype("Float64")
    
final

,STUDENT_ID,Batch,BWC_Status,Stream_Group,Stream_Unit,target_bwc,target_fighter,pred_bwc,prob_bwc,pred_fighter,prob_fighter
0,201EEZ,201,Fail,NaN,NaN,0.0,0.0,0.0,0.118992,0.0,0.0
1,201HLEE,201,Fail,NaN,NaN,0.0,0.0,0.0,0.065594,0.0,0.0
2,201HONT,201,Fail,NaN,NaN,0.0,0.0,1.0,0.881256,0.0,0.365022
3,201KOHJ,201,Fail,NaN,NaN,0.0,0.0,0.0,0.014283,0.0,0.0
4,201LIMK,201,Fail,NaN,NaN,0.0,0.0,1.0,0.752536,0.0,0.470441
5,201KHOOC,201,Pass,Heli,RWC,1.0,0.0,1.0,0.902146,1.0,0.523451
6,201KOHZ,201,Pass,Fighter,FWC,1.0,1.0,1.0,0.741961,1.0,0.699344
7,201KSARAN,201,Pass,Transport,TWC,1.0,0.0,1.0,0.938351,0.0,0.234078
8,201LEEJ,201,Pass,Fighter,FWC,1.0,1.0,1.0,0.939199,0.0,0.467614
9,201ONGE,201,Pass,Fighter,FWC,1.0,1.0,1.0,0.933237,1.0,0.536148
10,201PANGM,201,Pass,Heli,RWC,1.0,0.0,1.0,0.950481,1.0,0.539588
11,201TANGK,201,Pass,Transport,TWC,1.0,0.0,1.0,0.925688,0.0,0.440448
12,202CHUNGS,202,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.581293,1.0,0.81649
13,202HOJ,202,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.758449,0.0,0.468523
14,202LOHX,202,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.667165,1.0,0.722358
15,202PHUAC,202,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.569784,1.0,0.786162
16,202SOOE,202,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.638365,1.0,0.69992
17,202YUQ,202,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.589462,1.0,0.77984
18,202CHOWY,202,Fail,NaN,NaN,0.0,0.0,0.0,0.075443,0.0,0.0
19,202NEOY,202,Fail,NaN,NaN,0.0,0.0,0.0,0.109407,0.0,0.0
20,202ANGK,202,Pass,Heli,RWC,1.0,0.0,1.0,0.847806,0.0,0.459371
21,202CHUAL,202,Pass,Heli,RWC,1.0,0.0,1.0,0.92492,1.0,0.6515
22,202LEEL,202,Pass,Fighter,FWC,1.0,1.0,1.0,0.94949,1.0,0.522704
23,202LEEY,202,Pass,Transport,TWC,1.0,0.0,1.0,0.965429,0.0,0.461219
24,202NGJ,202,Pass,Fighter,ITAF,1.0,1.0,1.0,0.793785,1.0,0.787746
25,202POHK,202,Pass,Fighter,ITAF,1.0,1.0,1.0,0.929374,0.0,0.459833
26,202THAMY,202,Pass,Heli,IERW,1.0,0.0,1.0,0.946815,0.0,0.433368
27,202TOKJ,202,Pass,Fighter,FWC,1.0,1.0,1.0,0.891914,1.0,0.647568
28,203THONGW,203,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.619522,1.0,0.791595
29,203YNG,203,Fail,NaN,NaN,0.0,0.0,0.0,0.266485,0.0,0.0
30,203KTENG,203,Pass,Heli,RWC,1.0,0.0,1.0,0.883341,0.0,0.392214
31,203LIAUD,203,Pass,Heli,RWC,1.0,0.0,1.0,0.908036,0.0,0.467094
32,203LOHJ,203,Pass,Heli,IERW,1.0,0.0,1.0,0.86661,0.0,0.482921
33,203NGK,203,Pass,Fighter,FWC,1.0,1.0,1.0,0.8207,0.0,0.441863
34,203TANZ,203,Pass,Heli,RWC,1.0,0.0,1.0,0.897001,0.0,0.379446
35,204BOEYC,204,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.632856,1.0,0.843095
36,204NGZ,204,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.917728,1.0,0.609467
37,204TEOJ,204,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.543564,1.0,0.866148
38,204ONGS,204,Fail,NaN,NaN,0.0,0.0,0.0,0.482694,0.0,0.0
39,204SENGB,204,Fail,NaN,NaN,0.0,0.0,0.0,0.252143,0.0,0.0
40,204CHUAH,204,Pass,Fighter,FWC,1.0,1.0,1.0,0.888445,1.0,0.618136
41,204CKOH,204,Pass,Heli,RWC,1.0,0.0,1.0,0.93846,0.0,0.314927
42,204LIEWJ,204,Pass,Fighter,FWC,1.0,1.0,1.0,0.894321,1.0,0.589365
43,204ONGH,204,Pass,Transport,TWC,1.0,0.0,1.0,0.928247,0.0,0.44035
44,204ONGJ,204,Pass,Transport,TWC,1.0,0.0,1.0,0.934705,1.0,0.512174
45,204SEEY,204,Pass,Transport,TWC,1.0,0.0,1.0,0.898235,0.0,0.421307
46,204TANX,204,Pass,Fighter,FWC,1.0,1.0,1.0,0.921437,0.0,0.385723
47,205CHENX,205,Fail,NaN,NaN,0.0,0.0,0.0,0.081868,0.0,0.0
48,205EEC,205,Fail,NaN,NaN,0.0,0.0,0.0,0.098316,0.0,0.0
49,205LEEA,205,Fail,NaN,NaN,0.0,0.0,0.0,0.038936,0.0,0.0
50,205LEOWW,205,Fail,NaN,NaN,0.0,0.0,0.0,0.487422,0.0,0.0
51,205LOWC,205,Fail,NaN,NaN,0.0,0.0,0.0,0.062385,0.0,0.0
52,205YEOC,205,DNF(SUPT),Fighter,SUPT,1.0,1.0,0.0,0.417396,0.0,0.0
53,205LUIL,205,Pass,Fighter,FWC,1.0,1.0,1.0,0.84694,0.0,0.492902
54,205TANW,205,Pass,Heli,RWC,1.0,0.0,1.0,0.700473,0.0,0.469649
55,205TJOENGY,205,Pass,Transport,TWC,1.0,0.0,1.0,0.884242,0.0,0.402166
56,206CHOONGD,206,DNF(SUPT),Fighter,SUPT,1.0,1.0,1.0,0.559715,1.0,0.903805
57,206CHANY,206,Fail,NaN,NaN,0.0,0.0,0.0,0.051439,0.0,0.0
58,206MATHEWSL,206,Fail,NaN,NaN,0.0,0.0,0.0,0.111284,0.0,0.0
59,206TANA,206,Fail,NaN,NaN,0.0,0.0,0.0,0.034931,0.0,0.0

### Evaluation

In [14]:
final["pred_fighter"].value_counts(dropna=False)

pred_fighter
0.0    39
1.0    21
Name: count, dtype: Int64

In [15]:
print("Stage 1: Predict pass or fail BWC")
print(
    classification_report(
        final["target_bwc"].astype("Int64"),
        final["pred_bwc"].astype("Int64"),
        zero_division=0,
        digits=4,
    )
)
print(f"ROC-AUC: {roc_auc_score(final['target_bwc'], final['prob_bwc']):.4f}")
tn, fp, fn, tp = confusion_matrix(final["target_bwc"], final["pred_bwc"]).ravel()
print("Confusion Matrix:")
print(f"TN: {tn}, FP: {fp}")
print(f"FN: {fn}, TP: {tp}")

print()

print("Stage 2: Among predicted passes, predict streamed to fighter or not")
print(
    classification_report(
        final["target_fighter"].astype("Int64"),
        final["pred_fighter"].astype("Int64"),
        zero_division=0,
        digits=4,
    )
)
print(f"ROC-AUC: {roc_auc_score(final['target_fighter'], final['prob_fighter']):.4f}")
tn, fp, fn, tp = confusion_matrix(
    final["target_fighter"], final["pred_fighter"]
).ravel()
print("Confusion Matrix:")
print(f"TN: {tn}, FP: {fp}")
print(f"FN: {fn}, TP: {tp}")

Stage 1: Predict pass or fail BWC
              precision    recall  f1-score   support

         0.0     0.9412    0.8889    0.9143        18
         1.0     0.9535    0.9762    0.9647        42

    accuracy                         0.9500        60
   macro avg     0.9473    0.9325    0.9395        60
weighted avg     0.9498    0.9500    0.9496        60

ROC-AUC: 0.9577
Confusion Matrix:
TN: 16, FP: 2
FN: 1, TP: 41

Stage 2: Among predicted passes, predict streamed to fighter or not
              precision    recall  f1-score   support

         0.0     0.8205    0.8889    0.8533        36
         1.0     0.8095    0.7083    0.7556        24

    accuracy                         0.8167        60
   macro avg     0.8150    0.7986    0.8044        60
weighted avg     0.8161    0.8167    0.8142        60

ROC-AUC: 0.8958
Confusion Matrix:
TN: 32, FP: 4
FN: 7, TP: 17

In [16]:
final.to_csv("predictions/201-206_predictions_with_ground_truth.csv", index=False)