# EDA of clean, wide-span data

## Imports

In [11]:
import pandas as pd
import re
from collections.abc import Iterable
pd.set_option("display.max_columns", None)

## Constants

In [12]:
MODULE_1 = [
    "GH 1",
    "GH 2",
    "GH 3",
    "GH 4",
    "GH 5",
    "GH 6",
    "GH 7",
    "GH 8",
    "GH 9",
    "GH 10",
    "GH 11",
    "GH 12",
    "GH 13",
    "GH 14",
    "GH 15",
    "GH 17",
    "GH 19",
    "GH 21",
    "GH 22",
]

MODULE_2 = [
    "GH 24",
    "GH 25",
    "GH 27",
    "GH 28",
    "GH 29",
    "GH 30",
    "GH 31",
    "GH 32",
    "GH 33",
    "GH 34",
    "GHT",
]

MODULE_3 = ["IF 1", "IF 2", "IF 3", "IF 4", "IF 5", "IF 6", "IFT"]

MODULE_6 = ["AN 1", "AN 2", "AN 3", "AN 4", "AN 5", "AN 6", "AN 7"]

LESSONS_TO_KEEP = MODULE_1 + MODULE_2 + MODULE_3

In [13]:
FEATURE_SUFFIXES = [
    "score",
    "adjscore",
    "failed",
    "missing",
]

## Helper functions

In [14]:
def summarise_col(df, col):
    counts = df[col].value_counts(dropna=False)
    pct = df[col].value_counts(dropna=False, normalize=True).mul(100)
    summary = pd.DataFrame({
        "count": counts,
        "pct": pct.round(2)
    })
    print(summary)

In [15]:
def natural_sort_key(s):
    parts = re.split(r"(\d+)", str(s))
    return [int(p) if p.isdigit() else p for p in parts]

## Load data

In [16]:
df = pd.read_parquet("../data/03_clean/bwc_160_207.parquet")

In [17]:
df

,STUDENT_ID,GH 1_score,GH 1_adjscore,GH 1_failed,GH 1_missing,GH 2_score,GH 2_adjscore,GH 2_failed,GH 2_missing,GH 3_score,GH 3_adjscore,GH 3_failed,GH 3_missing,GH 4_score,GH 4_adjscore,GH 4_failed,GH 4_missing,GH 5_score,GH 5_adjscore,GH 5_failed,GH 5_missing,GH 6_score,GH 6_adjscore,GH 6_failed,GH 6_missing,GH 7_score,GH 7_adjscore,GH 7_failed,GH 7_missing,GH 8_score,GH 8_adjscore,GH 8_failed,GH 8_missing,GH 9_score,GH 9_adjscore,GH 9_failed,GH 9_missing,GH 10_score,GH 10_adjscore,GH 10_failed,GH 10_missing,GH 11_score,GH 11_adjscore,GH 11_failed,GH 11_missing,GH 12_score,GH 12_adjscore,GH 12_failed,GH 12_missing,GH 13_score,GH 13_adjscore,GH 13_failed,GH 13_missing,GH 14_score,GH 14_adjscore,GH 14_failed,GH 14_missing,GH 15_score,GH 15_adjscore,GH 15_failed,GH 15_missing,GH 17_score,GH 17_adjscore,GH 17_failed,GH 17_missing,GH 19_score,GH 19_adjscore,GH 19_failed,GH 19_missing,GH 21_score,GH 21_adjscore,GH 21_failed,GH 21_missing,GH 22_score,GH 22_adjscore,GH 22_failed,GH 22_missing,GH 24_score,GH 24_adjscore,GH 24_failed,GH 24_missing,GH 25_score,GH 25_adjscore,GH 25_failed,GH 25_missing,GH 27_score,GH 27_adjscore,GH 27_failed,GH 27_missing,GH 28_score,GH 28_adjscore,GH 28_failed,GH 28_missing,GH 29_score,GH 29_adjscore,GH 29_failed,GH 29_missing,GH 30_score,GH 30_adjscore,GH 30_failed,GH 30_missing,GH 31_score,GH 31_adjscore,GH 31_failed,GH 31_missing,GH 32_score,GH 32_adjscore,GH 32_failed,GH 32_missing,GH 33_score,GH 33_adjscore,GH 33_failed,GH 33_missing,GH 34_score,GH 34_adjscore,GH 34_failed,GH 34_missing,GHT_score,GHT_adjscore,GHT_failed,GHT_missing,IF 1_score,IF 1_adjscore,IF 1_failed,IF 1_missing,IF 2_score,IF 2_adjscore,IF 2_failed,IF 2_missing,IF 3_score,IF 3_adjscore,IF 3_failed,IF 3_missing,IF 4_score,IF 4_adjscore,IF 4_failed,IF 4_missing,IF 5_score,IF 5_adjscore,IF 5_failed,IF 5_missing,IF 6_score,IF 6_adjscore,IF 6_failed,IF 6_missing,IFT_score,IFT_adjscore,IFT_failed,IFT_missing,Batch,BWC_Status,Stream_Group,Stream_Unit,target_binary,target_multiclass,target_fighter
0,160CHANC,4.215324,4.215324,False,False,3.937536,3.937536,False,False,4.0,4.0,False,False,3.736023,3.736023,False,False,3.726859,3.726859,False,False,3.7472,3.7472,False,False,3.210893,1.0,True,False,2.673016,1.0,True,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,160,Fail,<NA>,<NA>,0,0,0
1,160CHANG,3.926446,3.926446,False,False,3.746286,3.746286,False,False,4.094832,4.094832,False,False,4.036967,4.036967,False,False,4.111887,4.111887,False,False,3.783657,3.783657,False,False,2.528977,2.528977,True,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,160,Fail,<NA>,<NA>,0,0,0
2,160CHOOC,4.243429,4.243429,False,False,4.37966,4.37966,False,False,4.674136,4.674136,False,False,4.110342,4.110342,False,False,3.962646,3.962646,False,False,3.928343,3.928343,False,False,4.0,4.0,False,False,4.107553,4.107553,False,False,4.304875,4.304875,False,False,4.3375,4.3375,False,False,4.40368,4.40368,False,False,4.367347,4.367347,False,False,4.050506,4.050506,False,False,4.409018,4.409018,False,False,4.0,4.0,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,160,DNF(SUPT),Fighter,SUPT,1,1,1
3,160HOS,4.556401,4.556401,False,False,4.476572,4.476572,False,False,4.458939,4.458939,False,False,3.850272,3.850272,False,False,4.074621,4.074621,False,False,4.110372,4.110372,False,False,4.385034,4.385034,False,False,4.229443,4.229443,False,False,4.486146,4.486146,False,False,4.228242,4.228242,False,False,4.039035,4.039035,False,False,4.0,4.0,False,False,4.202279,4.202279,False,False,4.0,4.0,False,False,4.0,4.0,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,160,DNF(SUPT),Fighter,SUPT,1,1,1
4,160HOWW,4.936332,4.936332,False,False,4.061821,4.061821,False,False,3.903645,3.903645,False,False,3.581086,3.581086,False,False,3.133589,3.133589,False,False,3.262857,3.262857,False,False,1.487395,1.0,True,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,160,Fail,<NA>,<NA>,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,205LUIL,4.924317,4.924317,False,False,<NA>,<NA>,<NA>,True,4.917947,4.917947,False,False,4.770194,4.770194,False,False,5.124462,5.124462,False,False,5.023953,5.023953,False,False,4.858888,4.858888,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.306506,4.306506,False,False,5.133254,5.133254,False,False,4.458276,4.458276,False,False,4.231589,4.231589,False,False,<NA>,<NA>,<NA>,True,4.513114,4.513114,False,False,<NA>,<NA>,<NA>,True,4.455976,4.455976,False,False,4.820704,4.820704,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.260091,4.260091,False,False,<NA>,<NA>,<NA>,True,3.248045,3.248045,True,False,<NA>,<NA>,<NA>,True,4.503327,4.503327,False,False,<NA>,<NA>,<NA>,True,3.766832,3.766832,True,False,4.426746,4.426746,False,False,4.628361,4.628361,False,False,4.78025,4.78025,False,False,4.617854,4.617854,True,False,<NA>,<NA>,<NA>,True,4.102874,4.102874,True,False,4.155668,4.155668,False,False,4.0,4.0,False,False,205,Pass,Fighter,FWC,1,1,1
697,205TANW,<NA>,<NA>,<NA>,True,5.793943,5.793943,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.704246,4.704246,False,False,4.854251,4.854251,False,False,<NA>,<NA>,<NA>,True,4.433442,4.433442,False,False,4.651561,4.651561,False,False,<NA>,<NA>,<NA>,True,4.80866,4.80866,False,False,4.253884,4.253884,False,False,4.372149,4.372149,False,False,5.419643,5.419643,False,False,4.106671,4.106671,False,False,4.0,4.0,False,False,<NA>,<NA>,<NA>,True,3.776876,3.776876,True,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,5.210476,5.210476,False,False,<NA>,<NA>,<NA>,True,4.224029,4.224029,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,3.832002,3.0,False,False,<NA>,<NA>,<NA>,True,4.258857,4.258857,False,False,205,Pass,Heli,RWC,1,3,0
698,205TJOENGY,<NA>,<NA>,<NA>,True,4.908005,4.908005,False,False,4.98627,4.98627,False,False,4.587764,4.587764,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,5.092737,5.092737,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.67272,4.67272,False,False,<NA>,<NA>,<NA>,True,4.397461,4.397461,False,False,4.202292,4.202292,False,False,<NA>,<NA>,<NA>,True,4.165772,4.165772,False,False,<NA>,<NA>,<NA>,True,4.0,4.0,False,False,<NA>,<NA>,<NA>,True,3.921762,1.0,True,False,4.354682,4.354682,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.397984,4.397984,False,False,<NA>,<NA>,<NA>,True,4.449851,4.449851,False,False,<NA>,<NA>,<NA>,True,4.736181,4.736181,False,False,4.388513,4.388513,False,False,3.938054,3.938054,False,False,<NA>,<NA>,<NA>,True,3.497153,1.0,True,False,205,Pass,Transport,TWC,1,2,0
699,205YEOC,5.97435,5.97435,False,False,6.025611,6.025611,False,False,5.163366,5.163366,False,False,5.348724,5.348724,False,False,5.842533,5.842533,False,False,<NA>,<NA>,<NA>,True,5.757143,5.757143,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,5.219336,5.219336,False,False,<NA>,<NA>,<NA>,True,5.530652,5.530652,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.87511,4.87511,False,False,4.848995,4.848995,False,False,4.461398,4.461398,False,False,5.076027,5.076027,False,False,5.028314,5.028314,False,False,5.426846,5.426846,False,False,<NA>,<NA>,<NA>,True,4.233145,4.233145,False,False,4.609333,4.609333,False,False,<NA>,<NA>,<NA>,True,4.768421,4.768421,False,False,<NA>,<NA>,<NA>,True,4.810052,4.810052,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,205,DNF(SUPT),Fighter,SUPT,1,1,1
700,206CHOONGD,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,4.503134,4.503134,False,False,<NA>,<NA>,<NA>,True,4.815092,4.815092,False,False,<NA>,<NA>,<NA>,True,4.27331,4.27331,False,False,4.485131,4.485131,False,False,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,True,206,DNF(SUPT),Fighter,SUPT,1,1,1

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 701 entries, 0 to 700
Columns: 156 entries, STUDENT_ID to target_fighter
dtypes: Float64(74), Int64(4), boolean(74), string(4)
memory usage: 615.9 KB

## Target distribution

What the values mean:

- 0: Fail BWC
- 1: Pass BWC, streamed to Fighter
- 2: Pass BWC, streamed to Transport
- 3: Pass BWC, streamed to Heli

The binary target is fairly balanced: 57.06% pass vs 42.94% fail. That means pass/fail modelling is not heavily affected by class imbalance, though a simple majority-class baseline would still get about 57% accuracy.

The multiclass target is more uneven. Fail is the largest class (42.94%), followed by Fighter (28.67%), Rotary (19.40%), and Transport (8.99%). The small Transport class will probably be the hardest to model well, so multiclass evaluation should pay more attention to macro F1 and per-class recall, not just overall accuracy.

At the batch level, there is quite a lot of variation in both pass rates and stream mix. Some batches have much higher pass rates than others, and the proportions of Fighter, Rotary, and Transport also shift across cohorts. This points to possible cohort effects and distribution shift, which could help explain why earlier models did not generalise well to unseen data.

Some of these swings may be due to small batch sizes, so not every difference should be overinterpreted. Still, the overall batch-to-batch variation is large enough to justify batch-aware validation. A random row-wise train/test split would likely give an overly optimistic result, so future-batch or batch-based validation is a better choice.

In [19]:
summarise_col(df, "target_binary")

               count    pct
target_binary
1                400  57.06
0                301  42.94

### Overall

In [23]:
summarise_col(df, "Stream_Group")
summarise_col(df, "Stream_Unit")
summarise_col(df, "target_binary")
summarise_col(df, "target_multiclass")
summarise_col(df[df["target_multiclass"] != 0],  "target_multiclass")

              count    pct
Stream_Group
<NA>            301  42.94
Fighter         201  28.67
Heli            136   19.4
Transport        63   8.99
             count    pct
Stream_Unit
<NA>           301  42.94
RWC            125  17.83
FWC            100  14.27
TWC             63   8.99
SUPT            49   6.99
NFTC            32   4.56
ITAF            20   2.85
IERW            11   1.57
               count    pct
target_binary
1                400  57.06
0                301  42.94
                   count    pct
target_multiclass
0                    301  42.94
1                    201  28.67
3                    136   19.4
2                     63   8.99
                   count    pct
target_multiclass
1                    201  50.25
3                    136   34.0
2                     63  15.75

### By BWC batch

In [24]:
for batch, group in df.groupby("Batch"):
    print(f"BWC Batch {batch}")
    print(f"num students: {len(group)}")
    summarise_col(group, "target_binary")
    summarise_col(group, "Stream_Group")
    print()

BWC Batch 160
num students: 18
               count    pct
target_binary
1                 10  55.56
0                  8  44.44
              count    pct
Stream_Group
Fighter           9   50.0
<NA>              8  44.44
Heli              1   5.56

BWC Batch 161
num students: 18
               count    pct
target_binary
1                 12  66.67
0                  6  33.33
              count    pct
Stream_Group
Heli              6  33.33
<NA>              6  33.33
Fighter           4  22.22
Transport         2  11.11

BWC Batch 162
num students: 13
               count    pct
target_binary
1                  8  61.54
0                  5  38.46
              count    pct
Stream_Group
Fighter           7  53.85
<NA>              5  38.46
Heli              1   7.69

BWC Batch 163
num students: 18
               count    pct
target_binary
0                 10  55.56
1                  8  44.44
              count    pct
Stream_Group
<NA>             10  55.56
Fighter           5  27.78
Heli              2  11.11
Transport         1   5.56

BWC Batch 164
num students: 17
               count    pct
target_binary
1                 12  70.59
0                  5  29.41
              count    pct
Stream_Group
Fighter          10  58.82
<NA>              5  29.41
Transport         1   5.88
Heli              1   5.88

BWC Batch 165
num students: 16
               count    pct
target_binary
0                  9  56.25
1                  7  43.75
              count    pct
Stream_Group
<NA>              9  56.25
Fighter           4   25.0
Heli              2   12.5
Transport         1   6.25

BWC Batch 166
num students: 18
               count   pct
target_binary
0                  9  50.0
1                  9  50.0
              count    pct
Stream_Group
<NA>              9   50.0
Heli              5  27.78
Fighter           3  16.67
Transport         1   5.56

BWC Batch 167
num students: 17
               count    pct
target_binary
1                 10  58.82
0                  7  41.18
              count    pct
Stream_Group
<NA>              7  41.18
Heli              5  29.41
Fighter           4  23.53
Transport         1   5.88

BWC Batch 168
num students: 14
               count    pct
target_binary
1                  8  57.14
0                  6  42.86
              count    pct
Stream_Group
<NA>              6  42.86
Fighter           3  21.43
Heli              3  21.43
Transport         2  14.29

BWC Batch 169
num students: 19
               count    pct
target_binary
1                 11  57.89
0                  8  42.11
              count    pct
Stream_Group
<NA>              8  42.11
Fighter           7  36.84
Heli              3  15.79
Transport         1   5.26

BWC Batch 170
num students: 15
               count    pct
target_binary
1                 11  73.33
0                  4  26.67
              count    pct
Stream_Group
Heli              7  46.67
<NA>              4  26.67
Fighter           3   20.0
Transport         1   6.67

BWC Batch 171
num students: 21
               count    pct
target_binary
1                 15  71.43
0                  6  28.57
              count    pct
Stream_Group
Fighter          10  47.62
<NA>              6  28.57
Heli              3  14.29
Transport         2   9.52

BWC Batch 172
num students: 20
               count   pct
target_binary
0                 14  70.0
1                  6  30.0
              count   pct
Stream_Group
<NA>             14  70.0
Heli              3  15.0
Fighter           2  10.0
Transport         1   5.0

BWC Batch 173
num students: 12
               count   pct
target_binary
0                  6  50.0
1                  6  50.0
              count    pct
Stream_Group
<NA>              6   50.0
Fighter           3   25.0
Heli              2  16.67
Transport         1   8.33

BWC Batch 174
num students: 11
               count    pct
target_binary
1                  7  63.64
0                  4  36.36
              count    pct
Stream_Group
<NA>              4  36.36
Heli              3  27.27
Transport         2  18.18
Fighter           2  18.18

BWC Batch 175
num students: 12
               count   pct
target_binary
1                  6  50.0
0                  6  50.0
              count    pct
Stream_Group
<NA>              6   50.0
Fighter           3   25.0
Heli              2  16.67
Transport         1   8.33

BWC Batch 176
num students: 20
               count   pct
target_binary
0                 10  50.0
1                 10  50.0
              count   pct
Stream_Group
<NA>             10  50.0
Heli              4  20.0
Fighter           4  20.0
Transport         2  10.0

BWC Batch 177
num students: 14
               count    pct
target_binary
0                  8  57.14
1                  6  42.86
              count    pct
Stream_Group
<NA>              8  57.14
Heli              4  28.57
Fighter           2  14.29

BWC Batch 178
num students: 13
               count    pct
target_binary
0                  7  53.85
1                  6  46.15
              count    pct
Stream_Group
<NA>              7  53.85
Heli              3  23.08
Fighter           3  23.08

BWC Batch 179
num students: 9
               count    pct
target_binary
1                  7  77.78
0                  2  22.22
              count    pct
Stream_Group
Fighter           4  44.44
Transport         3  33.33
<NA>              2  22.22

BWC Batch 180
num students: 15
               count    pct
target_binary
1                 11  73.33
0                  4  26.67
              count    pct
Stream_Group
Heli              7  46.67
<NA>              4  26.67
Fighter           3   20.0
Transport         1   6.67

BWC Batch 181
num students: 14
               count    pct
target_binary
1                 12  85.71
0                  2  14.29
              count    pct
Stream_Group
Heli              6  42.86
Fighter           4  28.57
<NA>              2  14.29
Transport         2  14.29

BWC Batch 182
num students: 18
               count    pct
target_binary
0                 11  61.11
1                  7  38.89
              count    pct
Stream_Group
<NA>             11  61.11
Fighter           3  16.67
Heli              3  16.67
Transport         1   5.56

BWC Batch 183
num students: 17
               count    pct
target_binary
1                 11  64.71
0                  6  35.29
              count    pct
Stream_Group
<NA>              6  35.29
Heli              5  29.41
Fighter           5  29.41
Transport         1   5.88

BWC Batch 184
num students: 12
               count    pct
target_binary
0                  8  66.67
1                  4  33.33
              count    pct
Stream_Group
<NA>              8  66.67
Heli              3   25.0
Transport         1   8.33

BWC Batch 185
num students: 18
               count    pct
target_binary
0                 13  72.22
1                  5  27.78
              count    pct
Stream_Group
<NA>             13  72.22
Transport         3  16.67
Heli              1   5.56
Fighter           1   5.56

BWC Batch 186
num students: 16
               count   pct
target_binary
0                  8  50.0
1                  8  50.0
              count    pct
Stream_Group
<NA>              8   50.0
Transport         4   25.0
Fighter           3  18.75
Heli              1   6.25

BWC Batch 187
num students: 19
               count    pct
target_binary
1                 11  57.89
0                  8  42.11
              count    pct
Stream_Group
<NA>              8  42.11
Heli              6  31.58
Fighter           5  26.32

BWC Batch 188
num students: 13
               count    pct
target_binary
1                  8  61.54
0                  5  38.46
              count    pct
Stream_Group
<NA>              5  38.46
Fighter           4  30.77
Heli              3  23.08
Transport         1   7.69

BWC Batch 189
num students: 13
               count    pct
target_binary
1                 10  76.92
0                  3  23.08
              count    pct
Stream_Group
Fighter           6  46.15
<NA>              3  23.08
Transport         2  15.38
Heli              2  15.38

BWC Batch 190
num students: 18
               count    pct
target_binary
0                 12  66.67
1                  6  33.33
              count    pct
Stream_Group
<NA>             12  66.67
Fighter           4  22.22
Heli              2  11.11

BWC Batch 191
num students: 12
               count   pct
target_binary
1                  6  50.0
0                  6  50.0
              count    pct
Stream_Group
<NA>              6   50.0
Fighter           4  33.33
Heli              2  16.67

BWC Batch 192
num students: 17
               count    pct
target_binary
1                 13  76.47
0                  4  23.53
              count    pct
Stream_Group
Fighter           7  41.18
<NA>              4  23.53
Transport         3  17.65
Heli              3  17.65

BWC Batch 193
num students: 17
               count    pct
target_binary
0                 11  64.71
1                  6  35.29
              count    pct
Stream_Group
<NA>             11  64.71
Fighter           4  23.53
Heli              1   5.88
Transport         1   5.88

BWC Batch 194
num students: 16
               count   pct
target_binary
0                 10  62.5
1                  6  37.5
              count   pct
Stream_Group
<NA>             10  62.5
Transport         2  12.5
Fighter           2  12.5
Heli              2  12.5

BWC Batch 195
num students: 17
               count    pct
target_binary
1                  9  52.94
0                  8  47.06
              count    pct
Stream_Group
<NA>              8  47.06
Fighter           6  35.29
Heli              2  11.76
Transport         1   5.88

BWC Batch 196
num students: 17
               count    pct
target_binary
1                  9  52.94
0                  8  47.06
              count    pct
Stream_Group
<NA>              8  47.06
Fighter           4  23.53
Transport         3  17.65
Heli              2  11.76

BWC Batch 197
num students: 16
               count    pct
target_binary
1                 11  68.75
0                  5  31.25
              count    pct
Stream_Group
Fighter           5  31.25
<NA>              5  31.25
Heli              4   25.0
Transport         2   12.5

BWC Batch 198
num students: 14
               count    pct
target_binary
1                 10  71.43
0                  4  28.57
              count    pct
Stream_Group
Fighter           6  42.86
<NA>              4  28.57
Heli              4  28.57

BWC Batch 199
num students: 15
               count   pct
target_binary
1                  9  60.0
0                  6  40.0
              count    pct
Stream_Group
<NA>              6   40.0
Fighter           4  26.67
Heli              3   20.0
Transport         2  13.33

BWC Batch 200
num students: 16
               count    pct
target_binary
1                 11  68.75
0                  5  31.25
              count    pct
Stream_Group
Fighter           5  31.25
<NA>              5  31.25
Heli              3  18.75
Transport         3  18.75

BWC Batch 201
num students: 11
               count    pct
target_binary
1                  7  63.64
0                  4  36.36
              count    pct
Stream_Group
<NA>              4  36.36
Fighter           3  27.27
Heli              2  18.18
Transport         2  18.18

BWC Batch 202
num students: 16
               count   pct
target_binary
1                 14  87.5
0                  2  12.5
              count    pct
Stream_Group
Fighter          10   62.5
Heli              3  18.75
<NA>              2   12.5
Transport         1   6.25

BWC Batch 203
num students: 7
               count    pct
target_binary
1                  6  85.71
0                  1  14.29
              count    pct
Stream_Group
Heli              4  57.14
Fighter           2  28.57
<NA>              1  14.29

BWC Batch 204
num students: 12
               count    pct
target_binary
1                 10  83.33
0                  2  16.67
              count    pct
Stream_Group
Fighter           6   50.0
Transport         3   25.0
<NA>              2  16.67
Heli              1   8.33

BWC Batch 205
num students: 9
               count    pct
target_binary
0                  5  55.56
1                  4  44.44
              count    pct
Stream_Group
<NA>              5  55.56
Fighter           2  22.22
Heli              1  11.11
Transport         1  11.11

BWC Batch 206
num students: 1
               count    pct
target_binary
1                  1  100.0
              count    pct
Stream_Group
Fighter           1  100.0

## Feature distribution

In [25]:
def _existing_lesson_feature_cols(
    df: pd.DataFrame,
    lessons: Iterable[str],
    feature_suffixes: Iterable[str] = FEATURE_SUFFIXES,
) -> dict[str, dict[str, str]]:
    """
    Return mapping:
        {
            "GH 1": {
                "score": "GH 1_score",
                "missing": "GH 1_missing",
                ...
            },
            ...
        }
    Only includes columns that actually exist in df.
    """
    lesson_cols: dict[str, dict[str, str]] = {}

    for lesson in lessons:
        feature_map: dict[str, str] = {}
        for suffix in feature_suffixes:
            col = f"{lesson}_{suffix}"
            if col in df.columns:
                feature_map[suffix] = col

        if feature_map:
            lesson_cols[lesson] = feature_map

    return lesson_cols


def _safe_numeric(series: pd.Series) -> pd.Series:
    """Convert to numeric where possible."""
    return pd.to_numeric(series, errors="coerce")


def _safe_bool_rate(series: pd.Series) -> float:
    """
    Return proportion True among all non-missing values.
    If all values are missing, return pd.NA.
    """
    s = series.dropna()
    if s.empty:
        return pd.NA

    # Works for pandas BooleanDtype / bool / object booleans
    return float((s == True).mean())  # noqa: E712


def _safe_value_rate(series: pd.Series, value: object) -> float:
    """
    Return proportion equal to `value` among all non-missing values.
    If all values are missing, return pd.NA.
    """
    s = series.dropna()
    if s.empty:
        return pd.NA
    return float((s == value).mean())


def summarize_key_features_by_col(
    merged: pd.DataFrame,
    lessons_to_keep: list[str],
    batch_col: str = "Batch",
) -> pd.DataFrame:
    """
    Create one long summary table with one row per Batch x Lesson.
    """
    if batch_col not in merged.columns:
        raise KeyError(f"'{batch_col}' not found in dataframe.")

    lesson_feature_map = _existing_lesson_feature_cols(merged, lessons_to_keep)

    if not lesson_feature_map:
        raise ValueError("No lesson feature columns found for the supplied lessons.")

    summary_rows: list[dict[str, object]] = []

    for batch_value, batch_df in merged.groupby(batch_col, dropna=False):
        n_students = len(batch_df)

        for lesson, cols in lesson_feature_map.items():
            row: dict[str, object] = {
                f"{batch_col}": batch_value,
                "lesson": lesson,
                "n_students": n_students,
            }

            # ---- score summary ----
            if "score" in cols:
                s = _safe_numeric(batch_df[cols["score"]])
                row["score_non_null_n"] = int(s.notna().sum())
                row["score_missing_n"] = int(s.isna().sum())
                row["score_mean"] = s.mean()
                row["score_std"] = s.std()
                row["score_median"] = s.median()
                row["score_min"] = s.min()
                row["score_max"] = s.max()

            # ---- adjusted score summary ----
            if "adjscore" in cols:
                s = _safe_numeric(batch_df[cols["adjscore"]])
                row["adjscore_non_null_n"] = int(s.notna().sum())
                row["adjscore_mean"] = s.mean()
                row["adjscore_std"] = s.std()
                row["adjscore_median"] = s.median()
                row["adjscore_min"] = s.min()
                row["adjscore_max"] = s.max()

            # ---- missingness ----
            if "missing" in cols:
                s = batch_df[cols["missing"]]
                row["missing_rate"] = _safe_bool_rate(s)


            # ---- flags ----
            if "failed" in cols:
                row["fail_rate"] = _safe_bool_rate(batch_df[cols["failed"]])

            summary_rows.append(row)

    summary_df = pd.DataFrame(summary_rows).sort_values(
        [f"{batch_col}", "lesson"],
        kind="stable",
    )

    return summary_df.reset_index(drop=True)

### By Stream_Unit

- Highest missingness:
  - NaN: Failures fail at earlier stages, hence high missingness for later scores.
  - With NaN removed, SUPT: High missingness due to SUPT trainees being taken out of BWC earlier.
- Highest fail rate:
  - NaN: The more sorties a trainee fails, the more likely the trainee will fail BWC.
  - With NaN removed, TWC: Supports the notion that the worst-performing trainees get streamed to TWC.
- Highest mean score:
  - SUPT and fighter courses
- Highest mean attempts:
  - IERW dominates: ? People who have to retake tests a lot end up going to heli? but it could be due to Weather

In [26]:
stream_unit_feature_summary = summarize_key_features_by_col(
    merged=df,
    lessons_to_keep=LESSONS_TO_KEEP,
    batch_col="Stream_Unit",
)

print(stream_unit_feature_summary.info())
stream_unit_feature_summary.to_csv("../data/04_EDA/stream_unit/stream_unit_feature_summary.csv", index=False)

<class 'pandas.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Stream_Unit          259 non-null    str
 1   lesson               296 non-null    str
 2   n_students           296 non-null    int64
 3   score_non_null_n     296 non-null    int64
 4   score_missing_n      296 non-null    int64
 5   score_mean           292 non-null    object
 6   score_std            290 non-null    object
 7   score_median         292 non-null    object
 8   score_min            292 non-null    object
 9   score_max            292 non-null    object
 10  adjscore_non_null_n  296 non-null    int64
 11  adjscore_mean        292 non-null    object
 12  adjscore_std         290 non-null    object
 13  adjscore_median      292 non-null    object
 14  adjscore_min         292 non-null    object
 15  adjscore_max         292 non-null    object
 16  missing_rate         296 non-null    float64
 17  fail_rate            292 non-null    object
dtypes: float64(1), int64(4), object(11), str(2)
memory usage: 44.0+ KB
None

#### Missingness

In [27]:
missing_rate_by_stream_unit = stream_unit_feature_summary.pivot(
    index="lesson",
    columns="Stream_Unit",
    values="missing_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
missing_rate_by_stream_unit = missing_rate_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest missing_rate for each lesson
missing_rate_by_stream_unit["highest_missing"] = missing_rate_by_stream_unit.idxmax(axis=1)

missing_rate_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit/missing_rate_by_stream_unit_lesson.csv"
)

summarise_col(missing_rate_by_stream_unit, "highest_missing")

missing_rate_by_stream_unit

                 count    pct
highest_missing
NaN                 19  51.35
SUPT                12  32.43
IERW                 3   8.11
ITAF                 3   8.11

Stream_Unit,NaN,FWC,IERW,ITAF,NFTC,RWC,SUPT,TWC,highest_missing
lesson,,,,,,,,,
GH 1,0.262458,0.30,0.181818,0.35,0.18750,0.216,0.387755,0.285714,SUPT
GH 2,0.262458,0.18,0.090909,0.30,0.18750,0.208,0.306122,0.253968,SUPT
GH 3,0.285714,0.24,0.363636,0.10,0.21875,0.184,0.387755,0.158730,SUPT
GH 4,0.318937,0.23,0.363636,0.30,0.18750,0.176,0.285714,0.206349,IERW
GH 5,0.322259,0.21,0.272727,0.30,0.25000,0.256,0.408163,0.301587,SUPT
GH 6,0.358804,0.28,0.272727,0.30,0.12500,0.240,0.224490,0.285714,NaN
GH 7,0.382060,0.28,0.181818,0.20,0.21875,0.272,0.285714,0.317460,NaN
GH 8,0.405316,0.38,0.454545,0.35,0.28125,0.264,0.408163,0.190476,IERW
GH 9,0.358804,0.21,0.181818,0.40,0.12500,0.184,0.265306,0.301587,ITAF
GH 10,0.448505,0.27,0.272727,0.45,0.25000,0.288,0.346939,0.349206,ITAF
GH 11,0.478405,0.30,0.181818,0.25,0.21875,0.240,0.265306,0.380952,NaN
GH 12,0.501661,0.19,0.272727,0.30,0.25000,0.304,0.367347,0.428571,NaN
GH 13,0.514950,0.23,0.363636,0.35,0.40625,0.224,0.285714,0.317460,NaN
GH 14,0.504983,0.26,0.181818,0.15,0.18750,0.280,0.346939,0.317460,NaN
GH 15,0.485050,0.24,0.000000,0.50,0.18750,0.232,0.367347,0.206349,ITAF
GH 17,0.584718,0.21,0.272727,0.30,0.12500,0.264,0.469388,0.285714,NaN
GH 19,0.548173,0.21,0.181818,0.30,0.15625,0.184,0.530612,0.238095,NaN
GH 21,0.750831,0.39,0.545455,0.45,0.65625,0.496,0.632653,0.523810,NaN
GH 22,0.614618,0.20,0.363636,0.25,0.28125,0.288,0.489796,0.333333,NaN
GH 24,0.667774,0.33,0.636364,0.55,0.31250,0.336,0.632653,0.460317,NaN
GH 25,0.691030,0.30,0.363636,0.40,0.18750,0.376,0.673469,0.380952,NaN
GH 27,0.737542,0.32,0.272727,0.35,0.40625,0.336,0.551020,0.492063,NaN
GH 28,0.744186,0.28,0.181818,0.25,0.31250,0.352,0.612245,0.285714,NaN
GH 29,0.754153,0.29,0.363636,0.15,0.18750,0.336,0.591837,0.476190,NaN
GH 30,0.936877,0.76,0.545455,0.60,0.90625,0.784,0.632653,0.777778,NaN
GH 31,0.873754,0.52,0.727273,0.70,0.21875,0.528,1.000000,0.587302,SUPT
GH 32,0.943522,0.67,0.636364,0.40,0.90625,0.760,0.571429,0.698413,NaN
GH 33,0.990033,0.93,1.000000,0.90,1.00000,0.944,1.000000,0.968254,IERW
GH 34,0.887043,0.24,0.090909,0.05,0.28125,0.288,0.734694,0.349206,NaN
GHT,0.810631,0.11,0.090909,0.35,0.15625,0.144,0.714286,0.206349,NaN
IF 1,0.770764,0.25,0.090909,0.10,0.21875,0.224,0.857143,0.206349,SUPT
IF 2,0.860465,0.26,0.090909,0.15,0.21875,0.208,0.938776,0.269841,SUPT
IF 3,0.857143,0.21,0.454545,0.20,0.21875,0.256,0.918367,0.174603,SUPT
IF 4,0.850498,0.23,0.272727,0.25,0.25000,0.256,0.959184,0.190476,SUPT
IF 5,0.877076,0.21,0.363636,0.20,0.15625,0.216,0.918367,0.206349,SUPT
IF 6,0.950166,0.48,0.181818,0.25,0.68750,0.672,0.979592,0.507937,SUPT
IFT,0.883721,0.22,0.454545,0.00,0.25000,0.216,0.979592,0.174603,SUPT

In [28]:
missing_rate_by_stream_unit = stream_unit_feature_summary.dropna(subset="Stream_Unit").pivot(
    index="lesson",
    columns="Stream_Unit",
    values="missing_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
missing_rate_by_stream_unit = missing_rate_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest missing_rate for each lesson
missing_rate_by_stream_unit["highest_missing"] = missing_rate_by_stream_unit.idxmax(axis=1)

missing_rate_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit_no_nans/missing_rate_by_stream_unit_lesson.csv"
)

summarise_col(missing_rate_by_stream_unit, "highest_missing")

missing_rate_by_stream_unit

                 count    pct
highest_missing
SUPT                22  59.46
IERW                 4  10.81
ITAF                 4  10.81
NFTC                 4  10.81
TWC                  3   8.11

Stream_Unit,FWC,IERW,ITAF,NFTC,RWC,SUPT,TWC,highest_missing
lesson,,,,,,,,
GH 1,0.30,0.181818,0.35,0.18750,0.216,0.387755,0.285714,SUPT
GH 2,0.18,0.090909,0.30,0.18750,0.208,0.306122,0.253968,SUPT
GH 3,0.24,0.363636,0.10,0.21875,0.184,0.387755,0.158730,SUPT
GH 4,0.23,0.363636,0.30,0.18750,0.176,0.285714,0.206349,IERW
GH 5,0.21,0.272727,0.30,0.25000,0.256,0.408163,0.301587,SUPT
GH 6,0.28,0.272727,0.30,0.12500,0.240,0.224490,0.285714,ITAF
GH 7,0.28,0.181818,0.20,0.21875,0.272,0.285714,0.317460,TWC
GH 8,0.38,0.454545,0.35,0.28125,0.264,0.408163,0.190476,IERW
GH 9,0.21,0.181818,0.40,0.12500,0.184,0.265306,0.301587,ITAF
GH 10,0.27,0.272727,0.45,0.25000,0.288,0.346939,0.349206,ITAF
GH 11,0.30,0.181818,0.25,0.21875,0.240,0.265306,0.380952,TWC
GH 12,0.19,0.272727,0.30,0.25000,0.304,0.367347,0.428571,TWC
GH 13,0.23,0.363636,0.35,0.40625,0.224,0.285714,0.317460,NFTC
GH 14,0.26,0.181818,0.15,0.18750,0.280,0.346939,0.317460,SUPT
GH 15,0.24,0.000000,0.50,0.18750,0.232,0.367347,0.206349,ITAF
GH 17,0.21,0.272727,0.30,0.12500,0.264,0.469388,0.285714,SUPT
GH 19,0.21,0.181818,0.30,0.15625,0.184,0.530612,0.238095,SUPT
GH 21,0.39,0.545455,0.45,0.65625,0.496,0.632653,0.523810,NFTC
GH 22,0.20,0.363636,0.25,0.28125,0.288,0.489796,0.333333,SUPT
GH 24,0.33,0.636364,0.55,0.31250,0.336,0.632653,0.460317,IERW
GH 25,0.30,0.363636,0.40,0.18750,0.376,0.673469,0.380952,SUPT
GH 27,0.32,0.272727,0.35,0.40625,0.336,0.551020,0.492063,SUPT
GH 28,0.28,0.181818,0.25,0.31250,0.352,0.612245,0.285714,SUPT
GH 29,0.29,0.363636,0.15,0.18750,0.336,0.591837,0.476190,SUPT
GH 30,0.76,0.545455,0.60,0.90625,0.784,0.632653,0.777778,NFTC
GH 31,0.52,0.727273,0.70,0.21875,0.528,1.000000,0.587302,SUPT
GH 32,0.67,0.636364,0.40,0.90625,0.760,0.571429,0.698413,NFTC
GH 33,0.93,1.000000,0.90,1.00000,0.944,1.000000,0.968254,IERW
GH 34,0.24,0.090909,0.05,0.28125,0.288,0.734694,0.349206,SUPT
GHT,0.11,0.090909,0.35,0.15625,0.144,0.714286,0.206349,SUPT
IF 1,0.25,0.090909,0.10,0.21875,0.224,0.857143,0.206349,SUPT
IF 2,0.26,0.090909,0.15,0.21875,0.208,0.938776,0.269841,SUPT
IF 3,0.21,0.454545,0.20,0.21875,0.256,0.918367,0.174603,SUPT
IF 4,0.23,0.272727,0.25,0.25000,0.256,0.959184,0.190476,SUPT
IF 5,0.21,0.363636,0.20,0.15625,0.216,0.918367,0.206349,SUPT
IF 6,0.48,0.181818,0.25,0.68750,0.672,0.979592,0.507937,SUPT
IFT,0.22,0.454545,0.00,0.25000,0.216,0.979592,0.174603,SUPT

#### Fail rate

In [29]:
fail_rate_by_stream_unit = stream_unit_feature_summary.pivot(
    index="lesson",
    columns="Stream_Unit",
    values="fail_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
fail_rate_by_stream_unit = fail_rate_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest fail_rate for each lesson
fail_rate_by_stream_unit["highest_fail_rate"] = fail_rate_by_stream_unit.idxmax(axis=1)

fail_rate_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit/fail_rate_by_stream_unit_lesson.csv"
)

summarise_col(fail_rate_by_stream_unit, "highest_fail_rate")

fail_rate_by_stream_unit

                   count    pct
highest_fail_rate
NaN                   16  43.24
TWC                    9  24.32
IERW                   8  21.62
RWC                    1   2.70
NFTC                   1   2.70
ITAF                   1   2.70
SUPT                   1   2.70

Stream_Unit,NaN,FWC,IERW,ITAF,NFTC,RWC,SUPT,TWC,highest_fail_rate
lesson,,,,,,,,,
GH 1,0.009009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
GH 2,0.018018,0.012195,0.0,0.0,0.0,0.020202,0.0,0.0,RWC
GH 3,0.018605,0.0,0.0,0.0,0.04,0.0,0.0,0.0,NFTC
GH 4,0.043902,0.012987,0.0,0.0,0.0,0.029126,0.0,0.0,NaN
GH 5,0.063725,0.063291,0.0,0.0,0.0,0.032258,0.0,0.090909,TWC
GH 6,0.11399,0.027778,0.125,0.0,0.0,0.021053,0.026316,0.066667,IERW
GH 7,0.080645,0.055556,0.111111,0.0,0.08,0.076923,0.028571,0.046512,IERW
GH 8,0.184358,0.032258,0.0,0.0,0.086957,0.152174,0.137931,0.098039,NaN
GH 9,0.238342,0.075949,0.111111,0.166667,0.071429,0.117647,0.0,0.181818,NaN
GH 10,0.066265,0.0,0.0,0.0,0.041667,0.011236,0.03125,0.0,NaN
GH 11,0.095541,0.028571,0.0,0.066667,0.08,0.063158,0.027778,0.025641,NaN
GH 12,0.106667,0.024691,0.125,0.0,0.041667,0.022989,0.032258,0.055556,IERW
GH 13,0.150685,0.038961,0.0,0.307692,0.0,0.092784,0.0,0.162791,ITAF
GH 14,0.080537,0.054054,0.0,0.0,0.038462,0.044444,0.0,0.069767,NaN
GH 15,0.129032,0.092105,0.181818,0.1,0.0,0.083333,0.032258,0.08,IERW
GH 17,0.112,0.063291,0.0,0.0,0.035714,0.065217,0.038462,0.133333,TWC
GH 19,0.161765,0.113924,0.111111,0.142857,0.074074,0.156863,0.043478,0.1875,TWC
GH 21,0.106667,0.032787,0.0,0.090909,0.0,0.031746,0.0,0.133333,TWC
GH 22,0.224138,0.025,0.0,0.066667,0.043478,0.146067,0.08,0.166667,NaN
GH 24,0.13,0.044776,0.0,0.0,0.0,0.072289,0.0,0.235294,TWC
GH 25,0.215054,0.157143,0.142857,0.0,0.153846,0.166667,0.3125,0.25641,SUPT
GH 27,0.126582,0.029412,0.125,0.0,0.0,0.096386,0.090909,0.125,NaN
GH 28,0.181818,0.041667,0.111111,0.133333,0.045455,0.049383,0.052632,0.111111,NaN
GH 29,0.189189,0.098592,0.428571,0.058824,0.192308,0.204819,0.0,0.272727,IERW
GH 30,0.210526,0.083333,0.0,0.0,0.0,0.407407,0.166667,0.5,TWC
GH 31,0.210526,0.104167,0.333333,0.0,0.04,0.152542,<NA>,0.230769,IERW
GH 32,0.411765,0.272727,0.0,0.083333,0.0,0.1,0.047619,0.105263,NaN
GH 33,0.666667,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,NaN
GH 34,0.058824,0.065789,0.2,0.0,0.0,0.022472,0.076923,0.0,IERW
GHT,0.298246,0.157303,0.2,0.076923,0.037037,0.196262,0.071429,0.18,NaN
IF 1,0.043478,0.0,0.0,0.0,0.0,0.010309,0.0,0.04,NaN
IF 2,0.0,0.027027,0.0,0.0,0.0,0.010101,0.0,0.043478,TWC
IF 3,0.046512,0.037975,0.0,0.0,0.0,0.021505,0.0,0.038462,NaN
IF 4,0.111111,0.0,0.125,0.0,0.0,0.075269,0.0,0.137255,TWC
IF 5,0.135135,0.050633,0.142857,0.0,0.037037,0.05102,0.0,0.08,IERW
IF 6,0.0,0.115385,0.111111,0.066667,0.0,0.146341,0.0,0.193548,TWC
IFT,0.285714,0.076923,0.166667,0.15,0.0,0.142857,0.0,0.153846,NaN

In [30]:
fail_rate_by_stream_unit = stream_unit_feature_summary.dropna(subset="Stream_Unit").pivot(
    index="lesson",
    columns="Stream_Unit",
    values="fail_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
fail_rate_by_stream_unit = fail_rate_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest fail_rate for each lesson
fail_rate_by_stream_unit["highest_fail_rate"] = fail_rate_by_stream_unit.idxmax(axis=1)

fail_rate_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit_no_nans/fail_rate_by_stream_unit_lesson.csv"
)

summarise_col(fail_rate_by_stream_unit, "highest_fail_rate")

fail_rate_by_stream_unit

                   count    pct
highest_fail_rate
TWC                   14  37.84
IERW                  11  29.73
FWC                    3   8.11
RWC                    3   8.11
NFTC                   3   8.11
ITAF                   2   5.41
SUPT                   1   2.70

Stream_Unit,FWC,IERW,ITAF,NFTC,RWC,SUPT,TWC,highest_fail_rate
lesson,,,,,,,,
GH 1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,FWC
GH 2,0.012195,0.0,0.0,0.0,0.020202,0.0,0.0,RWC
GH 3,0.0,0.0,0.0,0.04,0.0,0.0,0.0,NFTC
GH 4,0.012987,0.0,0.0,0.0,0.029126,0.0,0.0,RWC
GH 5,0.063291,0.0,0.0,0.0,0.032258,0.0,0.090909,TWC
GH 6,0.027778,0.125,0.0,0.0,0.021053,0.026316,0.066667,IERW
GH 7,0.055556,0.111111,0.0,0.08,0.076923,0.028571,0.046512,IERW
GH 8,0.032258,0.0,0.0,0.086957,0.152174,0.137931,0.098039,RWC
GH 9,0.075949,0.111111,0.166667,0.071429,0.117647,0.0,0.181818,TWC
GH 10,0.0,0.0,0.0,0.041667,0.011236,0.03125,0.0,NFTC
GH 11,0.028571,0.0,0.066667,0.08,0.063158,0.027778,0.025641,NFTC
GH 12,0.024691,0.125,0.0,0.041667,0.022989,0.032258,0.055556,IERW
GH 13,0.038961,0.0,0.307692,0.0,0.092784,0.0,0.162791,ITAF
GH 14,0.054054,0.0,0.0,0.038462,0.044444,0.0,0.069767,TWC
GH 15,0.092105,0.181818,0.1,0.0,0.083333,0.032258,0.08,IERW
GH 17,0.063291,0.0,0.0,0.035714,0.065217,0.038462,0.133333,TWC
GH 19,0.113924,0.111111,0.142857,0.074074,0.156863,0.043478,0.1875,TWC
GH 21,0.032787,0.0,0.090909,0.0,0.031746,0.0,0.133333,TWC
GH 22,0.025,0.0,0.066667,0.043478,0.146067,0.08,0.166667,TWC
GH 24,0.044776,0.0,0.0,0.0,0.072289,0.0,0.235294,TWC
GH 25,0.157143,0.142857,0.0,0.153846,0.166667,0.3125,0.25641,SUPT
GH 27,0.029412,0.125,0.0,0.0,0.096386,0.090909,0.125,IERW
GH 28,0.041667,0.111111,0.133333,0.045455,0.049383,0.052632,0.111111,ITAF
GH 29,0.098592,0.428571,0.058824,0.192308,0.204819,0.0,0.272727,IERW
GH 30,0.083333,0.0,0.0,0.0,0.407407,0.166667,0.5,TWC
GH 31,0.104167,0.333333,0.0,0.04,0.152542,<NA>,0.230769,IERW
GH 32,0.272727,0.0,0.083333,0.0,0.1,0.047619,0.105263,FWC
GH 33,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,FWC
GH 34,0.065789,0.2,0.0,0.0,0.022472,0.076923,0.0,IERW
GHT,0.157303,0.2,0.076923,0.037037,0.196262,0.071429,0.18,IERW
IF 1,0.0,0.0,0.0,0.0,0.010309,0.0,0.04,TWC
IF 2,0.027027,0.0,0.0,0.0,0.010101,0.0,0.043478,TWC
IF 3,0.037975,0.0,0.0,0.0,0.021505,0.0,0.038462,TWC
IF 4,0.0,0.125,0.0,0.0,0.075269,0.0,0.137255,TWC
IF 5,0.050633,0.142857,0.0,0.037037,0.05102,0.0,0.08,IERW
IF 6,0.115385,0.111111,0.066667,0.0,0.146341,0.0,0.193548,TWC
IFT,0.076923,0.166667,0.15,0.0,0.142857,0.0,0.153846,IERW

#### score_mean

In [31]:
score_mean_by_stream_unit = stream_unit_feature_summary.pivot(
    index="lesson",
    columns="Stream_Unit",
    values="score_mean",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
score_mean_by_stream_unit = score_mean_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest score_mean for each lesson
score_mean_by_stream_unit["highest_score"] = score_mean_by_stream_unit.idxmax(axis=1)

score_mean_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit/score_mean_by_stream_unit_lesson.csv"
)

summarise_col(score_mean_by_stream_unit, "highest_score")

score_mean_by_stream_unit

               count    pct
highest_score
SUPT              22  59.46
ITAF              10  27.03
FWC                2   5.41
NFTC               2   5.41
IERW               1   2.70

Stream_Unit,NaN,FWC,IERW,ITAF,NFTC,RWC,SUPT,TWC,highest_score
lesson,,,,,,,,,
GH 1,4.692296,4.949411,5.077998,5.268062,4.736339,4.802758,4.922199,4.849831,ITAF
GH 2,4.629744,5.056437,5.121626,5.064885,4.791849,4.760327,5.018525,4.804052,IERW
GH 3,4.376686,4.731431,4.317469,4.758475,4.548008,4.463989,4.769112,4.484887,SUPT
GH 4,4.370463,4.676477,4.441278,4.786229,4.530769,4.476667,4.688946,4.504464,ITAF
GH 5,4.214816,4.502656,4.592361,4.779708,4.578382,4.339215,4.655045,4.360977,ITAF
GH 6,4.162812,4.493043,4.32866,4.590176,4.238308,4.319181,4.435927,4.324963,ITAF
GH 7,4.196908,4.474836,4.386774,4.812234,4.285744,4.2743,4.57638,4.342752,ITAF
GH 8,4.108857,4.38431,4.038756,4.707248,4.246888,4.269862,4.405617,4.349025,ITAF
GH 9,4.083597,4.326781,4.220264,4.539312,4.309932,4.254437,4.564584,4.171841,SUPT
GH 10,4.292048,4.520666,4.269497,4.699244,4.408295,4.338707,4.545158,4.368342,ITAF
GH 11,4.273019,4.417284,4.356081,4.542644,4.467181,4.335146,4.621979,4.299706,SUPT
GH 12,4.185036,4.305986,4.277085,4.263786,4.238649,4.176581,4.44158,4.17957,SUPT
GH 13,4.111542,4.299102,4.122388,4.38345,4.326435,4.159529,4.520601,4.147616,SUPT
GH 14,4.175853,4.278334,4.099182,4.544413,4.261824,4.208265,4.572179,4.184158,SUPT
GH 15,4.26242,4.421169,4.298391,4.378815,4.353246,4.368967,4.528031,4.35766,SUPT
GH 17,4.237176,4.394934,4.104522,4.351983,4.34878,4.324058,4.500514,4.137951,SUPT
GH 19,4.169697,4.33277,4.273057,4.326876,4.279996,4.285837,4.499867,4.147638,SUPT
GH 21,4.114402,4.264489,4.131189,4.176631,4.305122,4.166316,4.539236,4.145493,SUPT
GH 22,4.16942,4.37333,4.38537,4.287826,4.351931,4.19479,4.597238,4.184872,SUPT
GH 24,4.031715,4.272661,4.196285,4.226704,4.094079,4.076731,4.330398,3.964484,SUPT
GH 25,4.1427,4.30689,4.055864,4.484061,4.198842,4.142516,4.240638,4.091873,ITAF
GH 27,4.187994,4.329843,4.425653,4.424677,4.283977,4.207261,4.490801,4.152426,SUPT
GH 28,4.212697,4.298815,4.236934,4.253597,4.262215,4.205115,4.52855,4.190906,SUPT
GH 29,4.142107,4.292729,3.646584,4.39768,4.18704,4.226632,4.453018,4.139242,SUPT
GH 30,4.323778,4.394265,4.487934,4.774641,4.597017,4.275581,4.414559,4.147816,ITAF
GH 31,4.158112,4.327844,3.909106,4.24032,4.25749,4.192112,<NA>,4.162053,FWC
GH 32,4.372948,4.376238,4.456358,4.588866,4.663335,4.448432,4.525119,4.419275,NFTC
GH 33,3.458607,3.99706,<NA>,3.956974,<NA>,3.943422,<NA>,3.745117,FWC
GH 34,4.30856,4.283889,4.253716,4.477377,4.34745,4.169045,4.288276,4.205676,ITAF
GHT,4.028241,4.233084,3.757149,4.229965,4.300732,4.069514,4.37073,4.117442,SUPT
IF 1,4.329157,4.650491,4.583656,4.708764,4.560868,4.50267,4.809068,4.386387,SUPT
IF 2,4.58049,4.657633,4.462566,4.813254,4.691614,4.460959,4.819158,4.528745,SUPT
IF 3,4.473723,4.624843,4.587019,4.619567,4.608964,4.379582,4.819604,4.476711,SUPT
IF 4,4.344287,4.443031,4.350337,4.533945,4.551845,4.190469,4.652543,4.272731,SUPT
IF 5,4.02448,4.236499,4.09762,4.352007,4.465084,4.128611,4.343711,4.116351,NFTC
IF 6,4.311631,4.157789,3.942892,4.189208,4.409991,4.151418,4.451751,4.090532,SUPT
IFT,4.056762,4.376099,4.275709,4.372259,4.375442,4.217888,4.500278,4.119818,SUPT

In [32]:
score_mean_by_stream_unit = stream_unit_feature_summary.dropna(subset="Stream_Unit").pivot(
    index="lesson",
    columns="Stream_Unit",
    values="score_mean",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
score_mean_by_stream_unit = score_mean_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest score_mean for each lesson
score_mean_by_stream_unit["highest_score"] = score_mean_by_stream_unit.idxmax(axis=1)

score_mean_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit_no_nans/score_mean_by_stream_unit_lesson.csv"
)

summarise_col(score_mean_by_stream_unit, "highest_score")

score_mean_by_stream_unit

               count    pct
highest_score
SUPT              22  59.46
ITAF              10  27.03
FWC                2   5.41
NFTC               2   5.41
IERW               1   2.70

Stream_Unit,FWC,IERW,ITAF,NFTC,RWC,SUPT,TWC,highest_score
lesson,,,,,,,,
GH 1,4.949411,5.077998,5.268062,4.736339,4.802758,4.922199,4.849831,ITAF
GH 2,5.056437,5.121626,5.064885,4.791849,4.760327,5.018525,4.804052,IERW
GH 3,4.731431,4.317469,4.758475,4.548008,4.463989,4.769112,4.484887,SUPT
GH 4,4.676477,4.441278,4.786229,4.530769,4.476667,4.688946,4.504464,ITAF
GH 5,4.502656,4.592361,4.779708,4.578382,4.339215,4.655045,4.360977,ITAF
GH 6,4.493043,4.32866,4.590176,4.238308,4.319181,4.435927,4.324963,ITAF
GH 7,4.474836,4.386774,4.812234,4.285744,4.2743,4.57638,4.342752,ITAF
GH 8,4.38431,4.038756,4.707248,4.246888,4.269862,4.405617,4.349025,ITAF
GH 9,4.326781,4.220264,4.539312,4.309932,4.254437,4.564584,4.171841,SUPT
GH 10,4.520666,4.269497,4.699244,4.408295,4.338707,4.545158,4.368342,ITAF
GH 11,4.417284,4.356081,4.542644,4.467181,4.335146,4.621979,4.299706,SUPT
GH 12,4.305986,4.277085,4.263786,4.238649,4.176581,4.44158,4.17957,SUPT
GH 13,4.299102,4.122388,4.38345,4.326435,4.159529,4.520601,4.147616,SUPT
GH 14,4.278334,4.099182,4.544413,4.261824,4.208265,4.572179,4.184158,SUPT
GH 15,4.421169,4.298391,4.378815,4.353246,4.368967,4.528031,4.35766,SUPT
GH 17,4.394934,4.104522,4.351983,4.34878,4.324058,4.500514,4.137951,SUPT
GH 19,4.33277,4.273057,4.326876,4.279996,4.285837,4.499867,4.147638,SUPT
GH 21,4.264489,4.131189,4.176631,4.305122,4.166316,4.539236,4.145493,SUPT
GH 22,4.37333,4.38537,4.287826,4.351931,4.19479,4.597238,4.184872,SUPT
GH 24,4.272661,4.196285,4.226704,4.094079,4.076731,4.330398,3.964484,SUPT
GH 25,4.30689,4.055864,4.484061,4.198842,4.142516,4.240638,4.091873,ITAF
GH 27,4.329843,4.425653,4.424677,4.283977,4.207261,4.490801,4.152426,SUPT
GH 28,4.298815,4.236934,4.253597,4.262215,4.205115,4.52855,4.190906,SUPT
GH 29,4.292729,3.646584,4.39768,4.18704,4.226632,4.453018,4.139242,SUPT
GH 30,4.394265,4.487934,4.774641,4.597017,4.275581,4.414559,4.147816,ITAF
GH 31,4.327844,3.909106,4.24032,4.25749,4.192112,<NA>,4.162053,FWC
GH 32,4.376238,4.456358,4.588866,4.663335,4.448432,4.525119,4.419275,NFTC
GH 33,3.99706,<NA>,3.956974,<NA>,3.943422,<NA>,3.745117,FWC
GH 34,4.283889,4.253716,4.477377,4.34745,4.169045,4.288276,4.205676,ITAF
GHT,4.233084,3.757149,4.229965,4.300732,4.069514,4.37073,4.117442,SUPT
IF 1,4.650491,4.583656,4.708764,4.560868,4.50267,4.809068,4.386387,SUPT
IF 2,4.657633,4.462566,4.813254,4.691614,4.460959,4.819158,4.528745,SUPT
IF 3,4.624843,4.587019,4.619567,4.608964,4.379582,4.819604,4.476711,SUPT
IF 4,4.443031,4.350337,4.533945,4.551845,4.190469,4.652543,4.272731,SUPT
IF 5,4.236499,4.09762,4.352007,4.465084,4.128611,4.343711,4.116351,NFTC
IF 6,4.157789,3.942892,4.189208,4.409991,4.151418,4.451751,4.090532,SUPT
IFT,4.376099,4.275709,4.372259,4.375442,4.217888,4.500278,4.119818,SUPT

#### mean_attempts

In [ ]:
mean_attempts_by_stream_unit = stream_unit_feature_summary.pivot(
    index="lesson",
    columns="Stream_Unit",
    values="mean_attempts",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
mean_attempts_by_stream_unit = mean_attempts_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest mean_attempts for each lesson
mean_attempts_by_stream_unit["highest_mean_attempts"] = mean_attempts_by_stream_unit.idxmax(axis=1)

mean_attempts_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit/mean_attempts_by_stream_unit_lesson.csv"
)

summarise_col(mean_attempts_by_stream_unit, "highest_mean_attempts")

mean_attempts_by_stream_unit

In [ ]:
mean_attempts_by_stream_unit = stream_unit_feature_summary.dropna(subset="Stream_Unit").pivot(
    index="lesson",
    columns="Stream_Unit",
    values="mean_attempts",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
mean_attempts_by_stream_unit = mean_attempts_by_stream_unit.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest mean_attempts for each lesson
mean_attempts_by_stream_unit["highest_mean_attempts"] = mean_attempts_by_stream_unit.idxmax(axis=1)

mean_attempts_by_stream_unit.to_csv(
    "../data/04_EDA/stream_unit_no_nans/mean_attempts_by_stream_unit_lesson.csv"
)

summarise_col(mean_attempts_by_stream_unit, "highest_mean_attempts")

mean_attempts_by_stream_unit

#### Compact

In [34]:
compact_stream_unit_feature_summary = stream_unit_feature_summary[
    [
        "Stream_Unit",
        "lesson",
        "n_students",
        "score_mean",
        "score_median",
        "missing_rate",
        "fail_rate",
    ]
].copy()
compact_stream_unit_feature_summary.to_csv("../data/04_EDA/stream_unit/compact_stream_unit_feature_summary.csv", index=False)
compact_stream_unit_feature_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 296 entries, 0 to 295
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stream_Unit   259 non-null    str
 1   lesson        296 non-null    str
 2   n_students    296 non-null    int64
 3   score_mean    292 non-null    object
 4   score_median  292 non-null    object
 5   missing_rate  296 non-null    float64
 6   fail_rate     292 non-null    object
dtypes: float64(1), int64(1), object(3), str(2)
memory usage: 18.6+ KB

### By Stream_Group

- Highest missingness:
  - NaN: Failures fail at earlier stages, hence high missingness for later scores.
  - With NaN removed, Fighter: High missingness due to SUPT.
- Highest fail rate:
  - NaN: The more sorties a trainee fails, the more likely the trainee will fail BWC.
  - With NaN removed, Transport: Supports the notion that the worst-performing trainees get streamed to Transport.
  - Supported by Transport having the highest DNCO and NG rates.
- Highest mean score:
  - Fighter: supports the notion that the best-performing trainees get streamed to Fighter
- Lowest mean score:
  - NaN: Trainees who achieve low scores fail BWC
  - With NaN removed, even split between heli and transport
- Highest mean attempts:
  - Heli: ? People who have to retake tests a lot end up going to heli? but it could be due to Weather

In [35]:
stream_group_feature_summary = summarize_key_features_by_col(
    merged=df,
    lessons_to_keep=LESSONS_TO_KEEP,
    batch_col="Stream_Group",
)

print(stream_group_feature_summary.info())
stream_group_feature_summary.to_csv("../data/04_EDA/stream_group/stream_group_feature_summary.csv", index=False)

<class 'pandas.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Stream_Group         111 non-null    str
 1   lesson               148 non-null    str
 2   n_students           148 non-null    int64
 3   score_non_null_n     148 non-null    int64
 4   score_missing_n      148 non-null    int64
 5   score_mean           148 non-null    float64
 6   score_std            148 non-null    float64
 7   score_median         148 non-null    float64
 8   score_min            148 non-null    float64
 9   score_max            148 non-null    float64
 10  adjscore_non_null_n  148 non-null    int64
 11  adjscore_mean        148 non-null    float64
 12  adjscore_std         148 non-null    float64
 13  adjscore_median      148 non-null    float64
 14  adjscore_min         148 non-null    float64
 15  adjscore_max         148 non-null    float64
 16  missing_rate         148 non-null    float64
 17  fail_rate            148 non-null    float64
dtypes: float64(12), int64(4), str(2)
memory usage: 22.3 KB
None

#### Missingness

In [36]:
missing_rate_by_stream_group = stream_group_feature_summary.pivot(
    index="lesson",
    columns="Stream_Group",
    values="missing_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
missing_rate_by_stream_group = missing_rate_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest missing_rate for each lesson
missing_rate_by_stream_group["highest_missing"] = missing_rate_by_stream_group.idxmax(axis=1)

missing_rate_by_stream_group.to_csv(
    "../data/04_EDA/stream_group/missing_rate_by_stream_group_lesson.csv"
)

summarise_col(missing_rate_by_stream_group, "highest_missing")

missing_rate_by_stream_group

                 count   pct
highest_missing
NaN                 36  97.3
Fighter              1   2.7

Stream_Group       NaN   Fighter      Heli  Transport highest_missing
lesson
GH 1          0.262458  0.308458  0.213235   0.285714         Fighter
GH 2          0.262458  0.223881  0.198529   0.253968             NaN
GH 3          0.285714  0.258706  0.198529   0.158730             NaN
GH 4          0.318937  0.243781  0.191176   0.206349             NaN
GH 5          0.322259  0.273632  0.257353   0.301587             NaN
GH 6          0.358804  0.243781  0.242647   0.285714             NaN
GH 7          0.382060  0.263682  0.264706   0.317460             NaN
GH 8          0.405316  0.368159  0.279412   0.190476             NaN
GH 9          0.358804  0.228856  0.183824   0.301587             NaN
GH 10         0.448505  0.303483  0.286765   0.349206             NaN
GH 11         0.478405  0.273632  0.235294   0.380952             NaN
GH 12         0.501661  0.253731  0.301471   0.428571             NaN
GH 13         0.514950  0.283582  0.235294   0.317460             NaN
GH 14         0.504983  0.258706  0.272059   0.317460             NaN
GH 15         0.485050  0.288557  0.213235   0.206349             NaN
GH 17         0.584718  0.268657  0.264706   0.285714             NaN
GH 19         0.548173  0.288557  0.183824   0.238095             NaN
GH 21         0.750831  0.497512  0.500000   0.523810             NaN
GH 22         0.614618  0.288557  0.294118   0.333333             NaN
GH 24         0.667774  0.422886  0.360294   0.460317             NaN
GH 25         0.691030  0.383085  0.375000   0.380952             NaN
GH 27         0.737542  0.393035  0.330882   0.492063             NaN
GH 28         0.744186  0.363184  0.338235   0.285714             NaN
GH 29         0.754153  0.333333  0.338235   0.476190             NaN
GH 30         0.936877  0.736318  0.764706   0.777778             NaN
GH 31         0.873754  0.606965  0.544118   0.587302             NaN
GH 32         0.943522  0.656716  0.750000   0.698413             NaN
GH 33         0.990033  0.955224  0.948529   0.968254             NaN
GH 34         0.887043  0.348259  0.272059   0.349206             NaN
GHT           0.810631  0.288557  0.139706   0.206349             NaN
IF 1          0.770764  0.378109  0.213235   0.206349             NaN
IF 2          0.860465  0.407960  0.198529   0.269841             NaN
IF 3          0.857143  0.383085  0.272059   0.174603             NaN
IF 4          0.850498  0.412935  0.257353   0.190476             NaN
IF 5          0.877076  0.373134  0.227941   0.206349             NaN
IF 6          0.950166  0.611940  0.632353   0.507937             NaN
IFT           0.883721  0.388060  0.235294   0.174603             NaN

In [37]:
missing_rate_by_stream_group = stream_group_feature_summary.dropna(subset="Stream_Group").pivot(
    index="lesson",
    columns="Stream_Group",
    values="missing_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
missing_rate_by_stream_group = missing_rate_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest missing_rate for each lesson
missing_rate_by_stream_group["highest_missing"] = missing_rate_by_stream_group.idxmax(axis=1)

missing_rate_by_stream_group.to_csv(
    "../data/04_EDA/stream_group_no_nans/missing_rate_by_stream_group_lesson.csv"
)

summarise_col(missing_rate_by_stream_group, "highest_missing")

missing_rate_by_stream_group

                 count    pct
highest_missing
Transport           19  51.35
Fighter             16  43.24
Heli                 2   5.41

Stream_Group   Fighter      Heli  Transport highest_missing
lesson
GH 1          0.308458  0.213235   0.285714         Fighter
GH 2          0.223881  0.198529   0.253968       Transport
GH 3          0.258706  0.198529   0.158730         Fighter
GH 4          0.243781  0.191176   0.206349         Fighter
GH 5          0.273632  0.257353   0.301587       Transport
GH 6          0.243781  0.242647   0.285714       Transport
GH 7          0.263682  0.264706   0.317460       Transport
GH 8          0.368159  0.279412   0.190476         Fighter
GH 9          0.228856  0.183824   0.301587       Transport
GH 10         0.303483  0.286765   0.349206       Transport
GH 11         0.273632  0.235294   0.380952       Transport
GH 12         0.253731  0.301471   0.428571       Transport
GH 13         0.283582  0.235294   0.317460       Transport
GH 14         0.258706  0.272059   0.317460       Transport
GH 15         0.288557  0.213235   0.206349         Fighter
GH 17         0.268657  0.264706   0.285714       Transport
GH 19         0.288557  0.183824   0.238095         Fighter
GH 21         0.497512  0.500000   0.523810       Transport
GH 22         0.288557  0.294118   0.333333       Transport
GH 24         0.422886  0.360294   0.460317       Transport
GH 25         0.383085  0.375000   0.380952         Fighter
GH 27         0.393035  0.330882   0.492063       Transport
GH 28         0.363184  0.338235   0.285714         Fighter
GH 29         0.333333  0.338235   0.476190       Transport
GH 30         0.736318  0.764706   0.777778       Transport
GH 31         0.606965  0.544118   0.587302         Fighter
GH 32         0.656716  0.750000   0.698413            Heli
GH 33         0.955224  0.948529   0.968254       Transport
GH 34         0.348259  0.272059   0.349206       Transport
GHT           0.288557  0.139706   0.206349         Fighter
IF 1          0.378109  0.213235   0.206349         Fighter
IF 2          0.407960  0.198529   0.269841         Fighter
IF 3          0.383085  0.272059   0.174603         Fighter
IF 4          0.412935  0.257353   0.190476         Fighter
IF 5          0.373134  0.227941   0.206349         Fighter
IF 6          0.611940  0.632353   0.507937            Heli
IFT           0.388060  0.235294   0.174603         Fighter

#### Fail rate

In [38]:
fail_rate_by_stream_group = stream_group_feature_summary.pivot(
    index="lesson",
    columns="Stream_Group",
    values="fail_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
fail_rate_by_stream_group = fail_rate_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest fail_rate for each lesson
fail_rate_by_stream_group["highest_fail_rate"] = fail_rate_by_stream_group.idxmax(axis=1)

fail_rate_by_stream_group.to_csv(
    "../data/04_EDA/stream_group/fail_rate_by_stream_group_lesson.csv"
)

summarise_col(fail_rate_by_stream_group, "highest_fail_rate")

fail_rate_by_stream_group

                   count    pct
highest_fail_rate
NaN                   23  62.16
Transport             13  35.14
Heli                   1   2.70

Stream_Group       NaN   Fighter      Heli  Transport highest_fail_rate
lesson
GH 1          0.009009  0.000000  0.000000   0.000000               NaN
GH 2          0.018018  0.006410  0.018349   0.000000              Heli
GH 3          0.018605  0.006711  0.000000   0.000000               NaN
GH 4          0.043902  0.006579  0.027273   0.000000               NaN
GH 5          0.063725  0.034247  0.029703   0.090909         Transport
GH 6          0.113990  0.019737  0.029126   0.066667               NaN
GH 7          0.080645  0.047297  0.080000   0.046512               NaN
GH 8          0.184358  0.062992  0.142857   0.098039               NaN
GH 9          0.238342  0.064516  0.117117   0.181818               NaN
GH 10         0.066265  0.014286  0.010309   0.000000               NaN
GH 11         0.095541  0.041096  0.057692   0.025641               NaN
GH 12         0.106667  0.026667  0.031579   0.055556               NaN
GH 13         0.150685  0.048611  0.086538   0.162791         Transport
GH 14         0.080537  0.033557  0.040404   0.069767               NaN
GH 15         0.129032  0.062937  0.093458   0.080000               NaN
GH 17         0.112000  0.047619  0.060000   0.133333         Transport
GH 19         0.161765  0.097902  0.153153   0.187500         Transport
GH 21         0.106667  0.029703  0.029412   0.133333         Transport
GH 22         0.224138  0.041958  0.135417   0.166667               NaN
GH 24         0.130000  0.025862  0.068966   0.235294         Transport
GH 25         0.215054  0.161290  0.164706   0.256410         Transport
GH 27         0.126582  0.032787  0.098901   0.125000               NaN
GH 28         0.181818  0.054688  0.055556   0.111111               NaN
GH 29         0.189189  0.097015  0.222222   0.272727         Transport
GH 30         0.210526  0.094340  0.343750   0.500000         Transport
GH 31         0.210526  0.075949  0.161290   0.230769         Transport
GH 32         0.411765  0.159420  0.088235   0.105263               NaN
GH 33         0.666667  0.000000  0.000000   0.000000               NaN
GH 34         0.058824  0.045802  0.040404   0.000000               NaN
GHT           0.298246  0.118881  0.196581   0.180000               NaN
IF 1          0.043478  0.000000  0.009346   0.040000               NaN
IF 2          0.000000  0.016807  0.009174   0.043478         Transport
IF 3          0.046512  0.024194  0.020202   0.038462               NaN
IF 4          0.111111  0.000000  0.079208   0.137255         Transport
IF 5          0.135135  0.039683  0.057143   0.080000               NaN
IF 6          0.000000  0.089744  0.140000   0.193548         Transport
IFT           0.285714  0.073171  0.144231   0.153846               NaN

In [39]:
fail_rate_by_stream_group = stream_group_feature_summary.dropna(subset="Stream_Group").pivot(
    index="lesson",
    columns="Stream_Group",
    values="fail_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
fail_rate_by_stream_group = fail_rate_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest fail_rate for each lesson
fail_rate_by_stream_group["highest_fail_rate"] = fail_rate_by_stream_group.idxmax(axis=1)

fail_rate_by_stream_group.to_csv(
    "../data/04_EDA/stream_group_no_nans/fail_rate_by_stream_group_lesson.csv"
)

summarise_col(fail_rate_by_stream_group, "highest_fail_rate")

fail_rate_by_stream_group

                   count    pct
highest_fail_rate
Transport             24  64.86
Heli                   7  18.92
Fighter                6  16.22

Stream_Group   Fighter      Heli  Transport highest_fail_rate
lesson
GH 1          0.000000  0.000000   0.000000           Fighter
GH 2          0.006410  0.018349   0.000000              Heli
GH 3          0.006711  0.000000   0.000000           Fighter
GH 4          0.006579  0.027273   0.000000              Heli
GH 5          0.034247  0.029703   0.090909         Transport
GH 6          0.019737  0.029126   0.066667         Transport
GH 7          0.047297  0.080000   0.046512              Heli
GH 8          0.062992  0.142857   0.098039              Heli
GH 9          0.064516  0.117117   0.181818         Transport
GH 10         0.014286  0.010309   0.000000           Fighter
GH 11         0.041096  0.057692   0.025641              Heli
GH 12         0.026667  0.031579   0.055556         Transport
GH 13         0.048611  0.086538   0.162791         Transport
GH 14         0.033557  0.040404   0.069767         Transport
GH 15         0.062937  0.093458   0.080000              Heli
GH 17         0.047619  0.060000   0.133333         Transport
GH 19         0.097902  0.153153   0.187500         Transport
GH 21         0.029703  0.029412   0.133333         Transport
GH 22         0.041958  0.135417   0.166667         Transport
GH 24         0.025862  0.068966   0.235294         Transport
GH 25         0.161290  0.164706   0.256410         Transport
GH 27         0.032787  0.098901   0.125000         Transport
GH 28         0.054688  0.055556   0.111111         Transport
GH 29         0.097015  0.222222   0.272727         Transport
GH 30         0.094340  0.343750   0.500000         Transport
GH 31         0.075949  0.161290   0.230769         Transport
GH 32         0.159420  0.088235   0.105263           Fighter
GH 33         0.000000  0.000000   0.000000           Fighter
GH 34         0.045802  0.040404   0.000000           Fighter
GHT           0.118881  0.196581   0.180000              Heli
IF 1          0.000000  0.009346   0.040000         Transport
IF 2          0.016807  0.009174   0.043478         Transport
IF 3          0.024194  0.020202   0.038462         Transport
IF 4          0.000000  0.079208   0.137255         Transport
IF 5          0.039683  0.057143   0.080000         Transport
IF 6          0.089744  0.140000   0.193548         Transport
IFT           0.073171  0.144231   0.153846         Transport

#### score_mean

In [40]:
score_mean_by_stream_group = stream_group_feature_summary.pivot(
    index="lesson",
    columns="Stream_Group",
    values="score_mean",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
score_mean_by_stream_group = score_mean_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest score_mean for each lesson
score_mean_by_stream_group["highest_score"] = score_mean_by_stream_group.idxmax(axis=1)

# Get Stream Unit with the lowest score_mean for each lesson
numeric_cols = score_mean_by_stream_group.select_dtypes(include="number").columns

score_mean_by_stream_group["lowest_score"] = (
    score_mean_by_stream_group[numeric_cols].idxmin(axis=1)
)

score_mean_by_stream_group.to_csv(
    "../data/04_EDA/stream_group/score_mean_by_stream_group_lesson.csv"
)

summarise_col(score_mean_by_stream_group, "highest_score")
summarise_col(score_mean_by_stream_group, "lowest_score")

score_mean_by_stream_group

               count   pct
highest_score
Fighter           36  97.3
NaN                1   2.7
              count    pct
lowest_score
NaN              23  62.16
Transport        10  27.03
Heli              4  10.81

Stream_Group,NaN,Fighter,Heli,Transport,highest_score,lowest_score
lesson,,,,,,
GH 1,4.692296,4.933484,4.825909,4.849831,Fighter,NaN
GH 2,4.629744,5.004834,4.793473,4.804052,Fighter,NaN
GH 3,4.376686,4.711509,4.454579,4.484887,Fighter,NaN
GH 4,4.370463,4.664533,4.474415,4.504464,Fighter,NaN
GH 5,4.214816,4.571940,4.359266,4.360977,Fighter,NaN
GH 6,4.162812,4.440786,4.319917,4.324963,Fighter,NaN
GH 7,4.196908,4.503384,4.284423,4.342752,Fighter,NaN
GH 8,4.108857,4.397345,4.255713,4.349025,Fighter,NaN
GH 9,4.083597,4.395423,4.251666,4.171841,Fighter,NaN
GH 10,4.292048,4.521031,4.332999,4.368342,Fighter,NaN
GH 11,4.273019,4.489180,4.336958,4.299706,Fighter,NaN
GH 12,4.185036,4.319296,4.185044,4.179570,Fighter,Transport
GH 13,4.111542,4.364160,4.157029,4.147616,Fighter,NaN
GH 14,4.175853,4.368919,4.198348,4.184158,Fighter,NaN
GH 15,4.262420,4.429024,4.361712,4.357660,Fighter,NaN
GH 17,4.237176,4.400726,4.306495,4.137951,Fighter,Transport
GH 19,4.169697,4.349104,4.284800,4.147638,Fighter,Transport
GH 21,4.114402,4.308310,4.163733,4.145493,Fighter,NaN
GH 22,4.169420,4.400064,4.208686,4.184872,Fighter,NaN
GH 24,4.031715,4.244186,4.082228,3.964484,Fighter,Transport
GH 25,4.142700,4.292831,4.135380,4.091873,Fighter,Transport
GH 27,4.187994,4.361831,4.226461,4.152426,Fighter,Transport
GH 28,4.212697,4.321326,4.208297,4.190906,Fighter,Transport
GH 29,4.142107,4.309460,4.181517,4.139242,Fighter,Transport
GH 30,4.323778,4.470049,4.308761,4.147816,Fighter,Transport
GH 31,4.158112,4.298933,4.178418,4.162053,Fighter,NaN
GH 32,4.372948,4.471011,4.449364,4.419275,Fighter,NaN
GH 33,3.458607,3.988152,3.943422,3.745117,Fighter,NaN
GH 34,4.308560,4.323547,4.177598,4.205676,Fighter,Heli
GHT,4.028241,4.259049,4.042816,4.117442,Fighter,NaN
IF 1,4.329157,4.649838,4.510238,4.386387,Fighter,NaN
IF 2,4.580490,4.691075,4.461106,4.528745,Fighter,Heli
IF 3,4.473723,4.627244,4.392154,4.476711,Fighter,Heli
IF 4,4.344287,4.480271,4.203132,4.272731,Fighter,Heli
IF 5,4.024480,4.303553,4.126545,4.116351,Fighter,NaN
IF 6,4.311631,4.199934,4.113883,4.090532,NaN,Transport
IFT,4.056762,4.376356,4.221223,4.119818,Fighter,NaN

In [41]:
score_mean_by_stream_group = stream_group_feature_summary.dropna(subset="Stream_Group").pivot(
    index="lesson",
    columns="Stream_Group",
    values="score_mean",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
score_mean_by_stream_group = score_mean_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest score_mean for each lesson
score_mean_by_stream_group["highest_score"] = score_mean_by_stream_group.idxmax(axis=1)

# Get Stream Unit with the lowest score_mean for each lesson
numeric_cols = score_mean_by_stream_group.select_dtypes(include="number").columns

score_mean_by_stream_group["lowest_score"] = (
    score_mean_by_stream_group[numeric_cols].idxmin(axis=1)
)

score_mean_by_stream_group.to_csv(
    "../data/04_EDA/stream_group_no_nans/score_mean_by_stream_group_lesson.csv"
)

summarise_col(score_mean_by_stream_group, "highest_score")
summarise_col(score_mean_by_stream_group, "lowest_score")

score_mean_by_stream_group

               count    pct
highest_score
Fighter           37  100.0
              count    pct
lowest_score
Transport        23  62.16
Heli             14  37.84

Stream_Group   Fighter      Heli  Transport highest_score lowest_score
lesson
GH 1          4.933484  4.825909   4.849831       Fighter         Heli
GH 2          5.004834  4.793473   4.804052       Fighter         Heli
GH 3          4.711509  4.454579   4.484887       Fighter         Heli
GH 4          4.664533  4.474415   4.504464       Fighter         Heli
GH 5          4.571940  4.359266   4.360977       Fighter         Heli
GH 6          4.440786  4.319917   4.324963       Fighter         Heli
GH 7          4.503384  4.284423   4.342752       Fighter         Heli
GH 8          4.397345  4.255713   4.349025       Fighter         Heli
GH 9          4.395423  4.251666   4.171841       Fighter    Transport
GH 10         4.521031  4.332999   4.368342       Fighter         Heli
GH 11         4.489180  4.336958   4.299706       Fighter    Transport
GH 12         4.319296  4.185044   4.179570       Fighter    Transport
GH 13         4.364160  4.157029   4.147616       Fighter    Transport
GH 14         4.368919  4.198348   4.184158       Fighter    Transport
GH 15         4.429024  4.361712   4.357660       Fighter    Transport
GH 17         4.400726  4.306495   4.137951       Fighter    Transport
GH 19         4.349104  4.284800   4.147638       Fighter    Transport
GH 21         4.308310  4.163733   4.145493       Fighter    Transport
GH 22         4.400064  4.208686   4.184872       Fighter    Transport
GH 24         4.244186  4.082228   3.964484       Fighter    Transport
GH 25         4.292831  4.135380   4.091873       Fighter    Transport
GH 27         4.361831  4.226461   4.152426       Fighter    Transport
GH 28         4.321326  4.208297   4.190906       Fighter    Transport
GH 29         4.309460  4.181517   4.139242       Fighter    Transport
GH 30         4.470049  4.308761   4.147816       Fighter    Transport
GH 31         4.298933  4.178418   4.162053       Fighter    Transport
GH 32         4.471011  4.449364   4.419275       Fighter    Transport
GH 33         3.988152  3.943422   3.745117       Fighter    Transport
GH 34         4.323547  4.177598   4.205676       Fighter         Heli
GHT           4.259049  4.042816   4.117442       Fighter         Heli
IF 1          4.649838  4.510238   4.386387       Fighter    Transport
IF 2          4.691075  4.461106   4.528745       Fighter         Heli
IF 3          4.627244  4.392154   4.476711       Fighter         Heli
IF 4          4.480271  4.203132   4.272731       Fighter         Heli
IF 5          4.303553  4.126545   4.116351       Fighter    Transport
IF 6          4.199934  4.113883   4.090532       Fighter    Transport
IFT           4.376356  4.221223   4.119818       Fighter    Transport

#### adjscore_mean

In [42]:
adjscore_mean_by_stream_group = stream_group_feature_summary.pivot(
    index="lesson",
    columns="Stream_Group",
    values="adjscore_mean",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
adjscore_mean_by_stream_group = adjscore_mean_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest adjscore_mean for each lesson
adjscore_mean_by_stream_group["highest_score"] = adjscore_mean_by_stream_group.idxmax(axis=1)

# Get Stream Unit with the lowest adjscore_mean for each lesson
numeric_cols = adjscore_mean_by_stream_group.select_dtypes(include="number").columns

adjscore_mean_by_stream_group["lowest_score"] = (
    adjscore_mean_by_stream_group[numeric_cols].idxmin(axis=1)
)

adjscore_mean_by_stream_group.to_csv(
    "../data/04_EDA/stream_group/adjscore_mean_by_stream_group_lesson.csv"
)

summarise_col(adjscore_mean_by_stream_group, "highest_score")
summarise_col(adjscore_mean_by_stream_group, "lowest_score")

adjscore_mean_by_stream_group

               count    pct
highest_score
Fighter           35  94.59
Transport          1   2.70
NaN                1   2.70
              count    pct
lowest_score
NaN              24  64.86
Transport         8  21.62
Heli              5  13.51

Stream_Group,NaN,Fighter,Heli,Transport,highest_score,lowest_score
lesson,,,,,,
GH 1,4.678203,4.933484,4.825909,4.849831,Fighter,NaN
GH 2,4.604177,4.985875,4.789102,4.804052,Fighter,NaN
GH 3,4.351243,4.711509,4.443416,4.472758,Fighter,NaN
GH 4,4.316573,4.656039,4.474415,4.504464,Fighter,NaN
GH 5,4.089426,4.516425,4.333274,4.360977,Fighter,NaN
GH 6,4.021538,4.356059,4.309830,4.324963,Fighter,NaN
GH 7,4.046781,4.471931,4.143675,4.194831,Fighter,NaN
GH 8,3.978307,4.363080,4.227524,4.290974,Fighter,NaN
GH 9,3.992754,4.343182,4.251666,4.099548,Fighter,NaN
GH 10,4.172341,4.449316,4.307198,4.332906,Fighter,NaN
GH 11,4.195824,4.415009,4.302030,4.207481,Fighter,NaN
GH 12,3.988234,4.266158,4.111502,4.122424,Fighter,NaN
GH 13,3.998837,4.317448,4.101285,3.989637,Fighter,Transport
GH 14,4.092878,4.310790,4.130039,4.053528,Fighter,Transport
GH 15,4.096484,4.380979,4.361712,4.137149,Fighter,NaN
GH 17,4.163886,4.329449,4.245385,4.002493,Fighter,Transport
GH 19,4.083101,4.287180,4.122725,3.953650,Fighter,Transport
GH 21,4.014630,4.287729,4.080291,4.113412,Fighter,NaN
GH 22,4.031373,4.308477,4.208686,4.064012,Fighter,NaN
GH 24,3.905041,4.199234,3.996071,3.805416,Fighter,Transport
GH 25,4.009615,4.230090,4.027977,4.022086,Fighter,NaN
GH 27,4.120623,4.263185,4.049748,3.888267,Fighter,Transport
GH 28,4.048093,4.226401,4.089876,4.066916,Fighter,NaN
GH 29,3.909995,4.224558,4.030519,3.928235,Fighter,NaN
GH 30,3.857839,4.356649,3.864881,3.286290,Fighter,Transport
GH 31,4.158112,4.298933,4.129485,4.162053,Fighter,Heli
GH 32,3.820788,4.251253,4.326689,4.419275,Transport,NaN
GH 33,2.672868,3.988152,3.943422,3.745117,Fighter,NaN
GH 34,4.194822,4.251874,4.100237,4.168824,Fighter,Heli
GHT,3.780504,4.183856,3.980265,4.057442,Fighter,NaN
IF 1,4.300426,4.638956,4.510238,4.373530,Fighter,NaN
IF 2,4.580490,4.691075,4.397815,4.374111,Fighter,Transport
IF 3,4.416914,4.603921,4.333947,4.443582,Fighter,Heli
IF 4,4.210086,4.460351,4.033139,4.108973,Fighter,Heli
IF 5,3.796279,4.233409,4.087642,4.068692,Fighter,NaN
IF 6,4.311631,4.199423,3.912289,4.003028,NaN,Heli
IFT,3.876872,4.328393,4.221223,4.070147,Fighter,NaN

In [43]:
adjscore_mean_by_stream_group = stream_group_feature_summary.dropna(subset="Stream_Group").pivot(
    index="lesson",
    columns="Stream_Group",
    values="adjscore_mean",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
adjscore_mean_by_stream_group = adjscore_mean_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest adjscore_mean for each lesson
adjscore_mean_by_stream_group["highest_score"] = adjscore_mean_by_stream_group.idxmax(axis=1)

# Get Stream Unit with the lowest adjscore_mean for each lesson
numeric_cols = adjscore_mean_by_stream_group.select_dtypes(include="number").columns

adjscore_mean_by_stream_group["lowest_score"] = (
    adjscore_mean_by_stream_group[numeric_cols].idxmin(axis=1)
)

adjscore_mean_by_stream_group.to_csv(
    "../data/04_EDA/stream_group_no_nans/adjscore_mean_by_stream_group_lesson.csv"
)

summarise_col(adjscore_mean_by_stream_group, "highest_score")
summarise_col(adjscore_mean_by_stream_group, "lowest_score")

adjscore_mean_by_stream_group

               count   pct
highest_score
Fighter           36  97.3
Transport          1   2.7
              count    pct
lowest_score
Transport        19  51.35
Heli             17  45.95
Fighter           1   2.70

Stream_Group   Fighter      Heli  Transport highest_score lowest_score
lesson
GH 1          4.933484  4.825909   4.849831       Fighter         Heli
GH 2          4.985875  4.789102   4.804052       Fighter         Heli
GH 3          4.711509  4.443416   4.472758       Fighter         Heli
GH 4          4.656039  4.474415   4.504464       Fighter         Heli
GH 5          4.516425  4.333274   4.360977       Fighter         Heli
GH 6          4.356059  4.309830   4.324963       Fighter         Heli
GH 7          4.471931  4.143675   4.194831       Fighter         Heli
GH 8          4.363080  4.227524   4.290974       Fighter         Heli
GH 9          4.343182  4.251666   4.099548       Fighter    Transport
GH 10         4.449316  4.307198   4.332906       Fighter         Heli
GH 11         4.415009  4.302030   4.207481       Fighter    Transport
GH 12         4.266158  4.111502   4.122424       Fighter         Heli
GH 13         4.317448  4.101285   3.989637       Fighter    Transport
GH 14         4.310790  4.130039   4.053528       Fighter    Transport
GH 15         4.380979  4.361712   4.137149       Fighter    Transport
GH 17         4.329449  4.245385   4.002493       Fighter    Transport
GH 19         4.287180  4.122725   3.953650       Fighter    Transport
GH 21         4.287729  4.080291   4.113412       Fighter         Heli
GH 22         4.308477  4.208686   4.064012       Fighter    Transport
GH 24         4.199234  3.996071   3.805416       Fighter    Transport
GH 25         4.230090  4.027977   4.022086       Fighter    Transport
GH 27         4.263185  4.049748   3.888267       Fighter    Transport
GH 28         4.226401  4.089876   4.066916       Fighter    Transport
GH 29         4.224558  4.030519   3.928235       Fighter    Transport
GH 30         4.356649  3.864881   3.286290       Fighter    Transport
GH 31         4.298933  4.129485   4.162053       Fighter         Heli
GH 32         4.251253  4.326689   4.419275     Transport      Fighter
GH 33         3.988152  3.943422   3.745117       Fighter    Transport
GH 34         4.251874  4.100237   4.168824       Fighter         Heli
GHT           4.183856  3.980265   4.057442       Fighter         Heli
IF 1          4.638956  4.510238   4.373530       Fighter    Transport
IF 2          4.691075  4.397815   4.374111       Fighter    Transport
IF 3          4.603921  4.333947   4.443582       Fighter         Heli
IF 4          4.460351  4.033139   4.108973       Fighter         Heli
IF 5          4.233409  4.087642   4.068692       Fighter    Transport
IF 6          4.199423  3.912289   4.003028       Fighter         Heli
IFT           4.328393  4.221223   4.070147       Fighter    Transport

#### mean_attempts

In [ ]:
mean_attempts_by_stream_group = stream_group_feature_summary.pivot(
    index="lesson",
    columns="Stream_Group",
    values="mean_attempts",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
mean_attempts_by_stream_group = mean_attempts_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest mean_attempts for each lesson
mean_attempts_by_stream_group["highest_mean_attempts"] = mean_attempts_by_stream_group.idxmax(axis=1)

mean_attempts_by_stream_group.to_csv(
    "../data/04_EDA/stream_group/mean_attempts_by_stream_group_lesson.csv"
)

summarise_col(mean_attempts_by_stream_group, "highest_mean_attempts")

mean_attempts_by_stream_group

In [ ]:
mean_attempts_by_stream_group = stream_group_feature_summary.dropna(subset="Stream_Group").pivot(
    index="lesson",
    columns="Stream_Group",
    values="mean_attempts",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
mean_attempts_by_stream_group = mean_attempts_by_stream_group.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest mean_attempts for each lesson
mean_attempts_by_stream_group["highest_mean_attempts"] = mean_attempts_by_stream_group.idxmax(axis=1)

mean_attempts_by_stream_group.to_csv(
    "../data/04_EDA/stream_group_no_nans/mean_attempts_by_stream_group_lesson.csv"
)

summarise_col(mean_attempts_by_stream_group, "highest_mean_attempts")

mean_attempts_by_stream_group

#### Compact

In [44]:
compact_stream_group_feature_summary = stream_group_feature_summary[
    [
        "Stream_Group",
        "lesson",
        "n_students",
        "score_mean",
        "score_median",
        "missing_rate",
        "fail_rate",
    ]
].copy()
compact_stream_group_feature_summary.to_csv("../data/04_EDA/stream_group/compact_stream_group_feature_summary.csv", index=False)
compact_stream_group_feature_summary.info()

<class 'pandas.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Stream_Group  111 non-null    str
 1   lesson        148 non-null    str
 2   n_students    148 non-null    int64
 3   score_mean    148 non-null    float64
 4   score_median  148 non-null    float64
 5   missing_rate  148 non-null    float64
 6   fail_rate     148 non-null    float64
dtypes: float64(4), int64(1), str(2)
memory usage: 9.6 KB

### By Batch

- Missingness:
  - Some lessons were only introduced later: e.g. GH 30 and GH 32 are essentially 100% missing from batches 160–185, then become meaningfully populated from batch 186 onward. Or the lesson name changed and I failed to capture the original one?
  - Some lessons seem to have been removed in later batches: e.g. GH 31 from batch 186 onwards is essentially 100% missing
  - IF6 missing from 168 to 185
  - later lessons have higher missingness

In [46]:
batch_feature_summary = summarize_key_features_by_col(
    merged=df,
    lessons_to_keep=LESSONS_TO_KEEP,
    batch_col="Batch",
)

print(batch_feature_summary.info())
batch_feature_summary.to_csv("../data/04_EDA/batch/batch_feature_summary.csv", index=False)

<class 'pandas.DataFrame'>
RangeIndex: 1739 entries, 0 to 1738
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Batch                1739 non-null   int64
 1   lesson               1739 non-null   str
 2   n_students           1739 non-null   int64
 3   score_non_null_n     1739 non-null   int64
 4   score_missing_n      1739 non-null   int64
 5   score_mean           1566 non-null   object
 6   score_std            1551 non-null   object
 7   score_median         1566 non-null   object
 8   score_min            1566 non-null   object
 9   score_max            1566 non-null   object
 10  adjscore_non_null_n  1739 non-null   int64
 11  adjscore_mean        1566 non-null   object
 12  adjscore_std         1551 non-null   object
 13  adjscore_median      1566 non-null   object
 14  adjscore_min         1566 non-null   object
 15  adjscore_max         1566 non-null   object
 16  missing_rate         1739 non-null   float64
 17  fail_rate            1566 non-null   object
dtypes: float64(1), int64(5), object(11), str(1)
memory usage: 252.5+ KB
None

#### Missingness

In [47]:
missing_rate_by_batch = batch_feature_summary.pivot(
    index="lesson",
    columns="Batch",
    values="missing_rate",
)

# sort the lesson index naturally: GH 1, GH 2, ..., GH 10
missing_rate_by_batch = missing_rate_by_batch.sort_index(
    key=lambda idx: idx.map(natural_sort_key)
)

# Get Stream Unit with the highest missing_rate for each lesson
missing_rate_by_batch["highest_missing"] = missing_rate_by_batch.idxmax(axis=1)

missing_rate_by_batch.to_csv(
    "../data/04_EDA/batch/missing_rate_by_batch_lesson.csv"
)

summarise_col(missing_rate_by_batch, "highest_missing")

missing_rate_by_batch

                 count    pct
highest_missing
206                 28  75.68
160                  2   5.41
190                  1   2.70
170                  1   2.70
186                  1   2.70
162                  1   2.70
171                  1   2.70
187                  1   2.70
168                  1   2.70

Batch,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,highest_missing
lesson,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
GH 1,0.000000,0.000000,0.076923,0.111111,0.235294,0.3750,0.111111,0.117647,0.142857,0.105263,0.133333,0.000000,0.10,0.833333,0.363636,0.083333,0.05,0.214286,0.076923,0.000000,0.000000,0.142857,0.333333,0.294118,0.250000,0.500000,0.3750,0.473684,0.461538,0.384615,0.444444,0.583333,0.235294,0.529412,0.4375,0.176471,0.176471,0.4375,0.214286,0.333333,0.5625,0.545455,0.2500,0.571429,0.666667,0.444444,1.0,206
GH 2,0.055556,0.000000,0.000000,0.222222,0.235294,0.3125,0.222222,0.000000,0.000000,0.263158,0.066667,0.142857,0.15,0.500000,0.090909,0.000000,0.00,0.071429,0.153846,0.222222,0.200000,0.142857,0.111111,0.235294,0.250000,0.277778,0.2500,0.368421,0.230769,0.461538,0.444444,0.250000,0.470588,0.235294,0.1250,0.000000,0.352941,0.5625,0.357143,0.533333,0.5625,0.818182,0.3750,0.000000,0.500000,0.222222,1.0,206
GH 3,0.055556,0.000000,0.000000,0.277778,0.176471,0.2500,0.333333,0.235294,0.214286,0.263158,0.066667,0.095238,0.25,0.583333,0.272727,0.083333,0.00,0.071429,0.076923,0.111111,0.266667,0.000000,0.222222,0.117647,0.250000,0.333333,0.1875,0.157895,0.461538,0.384615,0.611111,0.250000,0.470588,0.294118,0.3125,0.352941,0.176471,0.3750,0.071429,0.333333,0.3750,0.727273,0.3125,0.571429,0.500000,0.333333,1.0,206
GH 4,0.000000,0.000000,0.000000,0.222222,0.176471,0.1875,0.111111,0.235294,0.142857,0.263158,0.066667,0.238095,0.25,0.250000,0.363636,0.000000,0.05,0.071429,0.000000,0.000000,0.200000,0.071429,0.166667,0.176471,0.333333,0.444444,0.6250,0.263158,0.230769,0.384615,0.500000,0.416667,0.352941,0.529412,0.3125,0.352941,0.235294,0.1875,0.428571,0.600000,0.3750,0.818182,0.1875,0.714286,0.416667,0.555556,1.0,206
GH 5,0.055556,0.000000,0.076923,0.333333,0.117647,0.5625,0.222222,0.117647,0.142857,0.210526,0.133333,0.190476,0.30,0.500000,0.090909,0.083333,0.05,0.142857,0.000000,0.000000,0.133333,0.142857,0.055556,0.470588,0.500000,0.444444,0.3750,0.631579,0.307692,0.846154,0.500000,0.083333,0.588235,0.411765,0.1875,0.294118,0.235294,0.3750,0.500000,0.200000,0.5000,0.909091,0.1875,0.857143,0.416667,0.444444,1.0,206
GH 6,0.000000,0.111111,0.000000,0.277778,0.000000,0.3125,0.166667,0.117647,0.214286,0.315789,0.133333,0.571429,0.30,0.500000,0.090909,0.000000,0.20,0.000000,0.076923,0.000000,0.200000,0.071429,0.333333,0.411765,0.666667,0.555556,0.3125,0.526316,0.153846,0.615385,0.722222,0.166667,0.352941,0.235294,0.4375,0.352941,0.411765,0.1875,0.500000,0.600000,0.1250,0.545455,0.2500,0.428571,0.333333,0.666667,1.0,206
GH 7,0.055556,0.111111,0.000000,0.500000,0.176471,0.3750,0.388889,0.294118,0.142857,0.421053,0.266667,0.428571,0.30,0.416667,0.272727,0.083333,0.20,0.071429,0.000000,0.111111,0.133333,0.285714,0.166667,0.294118,0.333333,0.500000,0.4375,0.368421,0.230769,0.615385,0.888889,0.166667,0.294118,0.235294,0.5625,0.352941,0.235294,0.4375,0.285714,0.533333,0.4375,0.909091,0.0625,0.714286,0.166667,0.444444,1.0,206
GH 8,0.166667,0.166667,0.076923,0.333333,0.176471,0.5625,0.277778,0.176471,0.142857,0.210526,0.333333,0.333333,0.20,0.333333,0.181818,0.166667,0.40,0.142857,0.153846,0.333333,0.266667,0.357143,0.277778,0.117647,0.416667,0.666667,0.5000,0.157895,0.461538,0.615385,1.000000,0.083333,0.411765,0.235294,0.7500,0.235294,0.470588,0.4375,0.571429,0.733333,0.1875,0.636364,0.1875,0.571429,0.416667,0.777778,1.0,190
GH 9,0.222222,0.166667,0.000000,0.055556,0.176471,0.3125,0.055556,0.058824,0.214286,0.052632,0.200000,0.190476,0.20,0.500000,0.454545,0.333333,0.20,0.214286,0.153846,0.444444,0.066667,0.000000,0.222222,0.529412,0.500000,0.611111,0.0000,0.315789,0.153846,0.538462,0.777778,0.416667,0.470588,0.294118,0.5000,0.352941,0.352941,0.3125,0.571429,0.466667,0.3125,0.272727,0.1875,0.142857,0.083333,0.555556,1.0,206
GH 10,0.277778,0.166667,0.000000,0.166667,0.411765,0.5000,0.277778,0.470588,0.285714,0.315789,0.333333,0.476190,0.40,0.333333,0.454545,0.250000,0.25,0.214286,0.076923,0.111111,0.200000,0.285714,0.111111,0.470588,0.250000,0.500000,0.5000,0.421053,0.615385,0.615385,0.277778,0.416667,0.764706,0.294118,0.6250,0.470588,0.647059,0.6250,0.428571,0.400000,0.3125,0.454545,0.1875,0.428571,0.083333,0.555556,1.0,206
GH 11,0.277778,0.166667,0.153846,0.166667,0.294118,0.5625,0.166667,0.294118,0.357143,0.315789,0.266667,0.238095,0.30,0.583333,0.454545,0.333333,0.25,0.285714,0.153846,0.222222,0.200000,0.357143,0.277778,0.235294,0.333333,0.722222,0.5000,0.473684,0.615385,0.538462,0.222222,0.166667,0.470588,0.705882,0.5000,0.411765,0.470588,0.4375,0.428571,0.733333,0.2500,0.727273,0.1875,0.285714,0.250000,0.555556,1.0,206
GH 12,0.277778,0.277778,0.153846,0.166667,0.352941,0.5625,0.277778,0.470588,0.357143,0.105263,0.333333,0.238095,0.35,0.250000,0.454545,0.166667,0.25,0.285714,0.230769,0.111111,0.333333,0.428571,0.277778,0.294118,0.666667,0.722222,0.3125,0.526316,0.692308,0.538462,0.555556,0.166667,0.588235,0.352941,0.3750,0.529412,0.588235,0.6875,0.214286,0.400000,0.6875,0.545455,0.1250,0.857143,0.333333,0.444444,1.0,206
GH 13,0.277778,0.277778,0.076923,0.222222,0.352941,0.5000,0.333333,0.235294,0.285714,0.210526,0.333333,0.190476,0.50,0.333333,0.545455,0.333333,0.35,0.285714,0.076923,0.111111,0.333333,0.642857,0.333333,0.588235,0.583333,0.611111,0.5000,0.368421,0.615385,0.538462,0.444444,0.250000,0.411765,0.352941,0.4375,0.470588,0.529412,0.5000,0.571429,0.333333,0.5625,0.363636,0.2500,0.142857,0.166667,0.333333,1.0,206
GH 14,0.277778,0.277778,0.076923,0.222222,0.470588,0.3750,0.666667,0.352941,0.428571,0.105263,0.466667,0.333333,0.30,0.250000,0.454545,0.416667,0.30,0.285714,0.153846,0.111111,0.333333,0.285714,0.333333,0.529412,0.666667,0.666667,0.3125,0.263158,0.538462,0.615385,0.222222,0.166667,0.588235,0.588235,0.6250,0.411765,0.588235,0.3125,0.428571,0.333333,0.2500,0.363636,0.2500,0.285714,0.166667,0.555556,1.0,206
GH 15,0.333333,0.277778,0.076923,0.166667,0.294118,0.3125,0.333333,0.176471,0.214286,0.210526,0.266667,0.190476,0.40,0.416667,0.363636,0.416667,0.45,0.285714,0.153846,0.000000,0.133333,0.142857,0.388889,0.470588,0.500000,0.500000,0.5000,0.315789,0.538462,0.461538,0.388889,0.416667,0.705882,0.588235,0.5000,0.411765,0.529412,0.2500,0.357143,0.400000,0.5625,0.181818,0.2500,0.142857,0.333333,0.555556,1.0,206
GH 17,0.500000,0.277778,0.384615,0.388889,0.352941,0.3125,0.333333,0.235294,0.428571,0.157895,0.600000,0.142857,0.70,0.333333,0.636364,0.333333,0.30,0.428571,0.153846,0.111111,0.200000,0.214286,0.277778,0.352941,0.916667,0.500000,0.5000,0.368421,0.846154,0.538462,0.555556,0.166667,0.588235,0.647059,0.4375,0.705882,0.294118,0.3125,0.500000,0.400000,0.5000,0.181818,0.3125,0.428571,0.333333,0.444444,1.0,206
GH 19,0.500000,0.222222,0.461538,0.333333,0.470588,0.3125,0.388889,0.411765,0.357143,0.157895,0.200000,0.095238,0.45,0.250000,0.363636,0.333333,0.30,0.500000,0.000000,0.000000,0.266667,0.357143,0.333333,0.411765,0.583333,0.722222,0.2500,0.263158,0.307692,0.538462,0.388889,0.166667,0.529412,0.470588,0.6250,0.411765,0.294118,0.4375,0.428571,0.266667,0.5625,0.363636,0.6875,0.285714,0.583333,0.444444,1.0,206
GH 21,0.500000,0.277778,0.461538,0.388889,0.294118,0.5625,0.277778,0.823529,0.714286,0.894737,1.000000,1.000000,1.00,0.250000,1.000000,0.916667,0.35,0.428571,0.384615,0.555556,0.266667,0.142857,0.333333,0.647059,0.750000,0.611111,0.5625,0.684211,1.000000,0.461538,0.666667,0.583333,0.764706,0.823529,0.6250,0.647059,0.705882,0.3125,0.500000,0.800000,0.6875,0.636364,0.7500,0.571429,0.750000,0.555556,1.0,170
GH 22,0.500000,0.388889,0.538462,0.333333,0.411765,0.4375,0.333333,0.352941,0.357143,0.157895,0.333333,0.380952,0.60,0.333333,0.454545,0.250000,0.35,0.428571,0.230769,0.222222,0.266667,0.142857,0.388889,0.352941,0.583333,0.666667,0.5000,0.263158,0.384615,0.538462,0.611111,0.333333,0.411765,0.647059,0.7500,0.588235,0.529412,0.3750,0.571429,0.466667,0.7500,0.363636,0.5000,0.428571,0.583333,0.333333,1.0,206
GH 24,0.500000,0.277778,0.538462,0.277778,0.588235,0.6250,0.444444,0.411765,0.571429,0.210526,0.200000,0.428571,0.55,0.500000,0.636364,0.500000,0.40,0.428571,0.307692,0.222222,0.666667,0.571429,0.388889,0.588235,0.666667,0.833333,0.6875,0.421053,0.692308,0.307692,0.666667,0.583333,0.529412,0.647059,0.5625,0.588235,0.470588,0.5625,0.642857,0.600000,0.7500,0.545455,0.6875,0.571429,0.500000,0.666667,1.0,206
GH 25,0.500000,0.277778,0.538462,0.500000,0.529412,0.6250,0.388889,0.235294,0.500000,0.421053,0.800000,0.333333,0.90,0.500000,0.727273,0.333333,0.35,0.500000,0.461538,0.111111,0.333333,0.285714,0.333333,0.294118,0.500000,0.888889,0.6250,0.526316,0.615385,0.307692,0.666667,0.500000,0.470588,0.588235,0.6250,0.588235,0.647059,0.9375,0.785714,0.400000,0.8125,0.181818,0.3125,0.428571,0.416667,0.777778,1.0,206
GH 27,0.555556,0.277778,0.615385,0.500000,0.588235,0.8125,0.444444,0.470588,0.500000,0.421053,0.400000,0.428571,0.70,0.250000,0.454545,0.333333,0.35,0.571429,0.461538,0.222222,0.600000,0.142857,0.388889,0.529412,0.833333,0.722222,0.5625,0.631579,0.692308,0.461538,0.722222,0.500000,0.470588,0.764706,0.4375,0.588235,0.764706,0.5625,0.428571,0.800000,0.8125,0.545455,0.3750,0.285714,0.833333,0.666667,1.0,206
GH 28,0.500000,0.277778,0.538462,0.500000,0.470588,0.6875,0.500000,0.411765,0.571429,0.315789,0.600000,0.619048,0.85,0.333333,0.636364,0.250000,0.40,0.571429,0.307692,0.333333,0.600000,0.214286,0.388889,0.352941,0.833333,0.611111,0.5625,0.684211,0.692308,0.384615,0.500000,0.500000,0.470588,0.529412,0.4375,0.705882,0.647059,0.5000,0.428571,0.666667,0.6250,0.545455,0.3125,0.571429,0.500000,0.666667,1.0,206
GH 29,0.500000,0.277778,0.538462,0.388889,0.470588,0.6250,0.555556,0.235294,0.500000,0.263158,0.466667,0.571429,0.85,0.500000,0.454545,0.416667,0.45,0.571429,0.384615,0.333333,0.533333,0.071429,0.500000,0.470588,0.750000,0.722222,0.6875,0.526316,0.769231,0.538462,0.666667,0.416667,0.411765,0.529412,0.7500,0.705882,0.529412,0.6250,0.428571,0.866667,0.6875,0.636364,0.2500,0.571429,0.500000,0.777778,1.0,206
GH 30,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.6875,0.789474,0.615385,0.461538,0.555556,0.583333,0.588235,0.588235,0.5000,0.882353,0.647059,0.5000,0.571429,0.533333,0.5000,0.636364,0.4375,0.571429,0.666667,0.555556,0.0,160
GH 31,0.500000,0.333333,0.538462,0.611111,0.529412,0.6250,0.555556,0.352941,0.500000,0.263158,0.533333,0.571429,0.75,0.333333,0.454545,0.333333,0.50,0.571429,0.461538,0.222222,0.600000,0.214286,0.388889,0.647059,0.666667,0.666667,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.0000,1.000000,1.000000,1.0000,1.000000,1.0000,1.000000,1.000000,1.000000,1.0,186
GH 32,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.6250,0.736842,0.461538,0.384615,0.666667,0.583333,0.294118,0.588235,0.7500,0.588235,0.529412,0.3750,0.571429,0.533333,0.2500,0.818182,0.3125,0.285714,0.416667,0.666667,0.0,160
GH 33,0.555556,0.277778,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.0000,1.000000,1.000000,1.0000,1.000000,1.0000,1.000000,1.000000,1.000000,1.0,162
GH 34,0.611111,0.500000,0.615385,0.722222,0.529412,0.6875,0.666667,0.529412,0.571429,0.421053,0.533333,0.809524,0.80,0.500000,0.363636,0.416667,0.60,0.571429,0.384615,0.444444,0.400000,0.357143,0.500000,0.529412,0.500000,0.777778,0.5625,0.789474,0.615385,0.538462,0.722222,0.583333,0.470588,0.764706,0.6250,0.411765,0.529412,0.3125,0.428571,0.533333,0.6250,0.545455,0.5000,0.571429,0.500000,0.555556,0.0,171
GHT,0.611111,0.388889,0.538462,0.444444,0.352941,0.6875,0.388889,0.235294,0.500000,0.157895,0.266667,0.333333,0.65,0.416667,0.363636,0.416667,0.45,0.500000,0.384615,0.222222,0.266667,0.142857,0.333333,0.411765,0.500000,0.611111,0.5625,0.894737,0.461538,0.538462,0.666667,0.500000,0.529412,0.705882,0.6250,0.529412,0.588235,0.3125,0.642857,0.600000,0.5000,0.454545,0.3125,0.428571,0.583333,0.888889,0.0,187
IF 1,0.500000,0.333333,0.692308,0.555556,0.588235,0.5000,0.388889,0.235294,0.500000,0.263158,0.266667,0.476190,0.80,0.250000,0.545455,0.250000,0.35,0.428571,0.230769,0.222222,0.400000,0.142857,0.444444,0.294118,0.583333,0.611111,0.8750,0.894737,0.307692,0.384615,0.722222,0.750000,0.529412,0.647059,0.5625,0.529412,0.470588,0.6875,0.500000,0.733333,0.4375,0.545455,0.5000,0.571429,0.500000,0.777778,1.0,206
IF 2,0.611111,0.388889,0.538462,0.611111,0.411765,0.6875,0.500000,0.411765,0.428571,0.315789,0.266667,0.476190,0.70,0.583333,0.636364,0.416667,0.45,0.571429,0.461538,0.222222,0.400000,0.357143,0.444444,0.470588,0.583333,0.611111,0.7500,0.736842,0.307692,0.692308,0.722222,0.666667,0.705882,0.705882,0.6250,0.823529,0.529412,0.6875,0.500000,0.666667,0.3750,0.454545,0.5000,0.571429,0.750000,0.888889,1.0,206
IF 3,0.666667,0.444444,0.538462,0.611111,0.470588,0.7500,0.555556,0.411765,0.571429,0.263158,0.266667,0.571429,0.75,0.583333,0.454545,0.416667,0.50,0.500000,0.538462,0.222222,0.333333,0.214286,0.388889,0.411765,0.666667,0.555556,0.4375,0.736842,0.307692,0.538462,0.777778,0.750000,0.529412,0.764706,0.7500,0.705882,0.588235,0.6250,0.428571,0.733333,0.4375,0.636364,0.6250,0.571429,0.583333,0.777778,1.0,206
IF 4,0.611111,0.277778,0.538462,0.555556,0.470588,0.6875,0.388889,0.411765,0.428571,0.473684,0.333333,0.666667,0.75,0.666667,0.454545,0.416667,0.45,0.500000,0.538462,0.333333,0.333333,0.214286,0.555556,0.529412,0.500000,0.555556,0.6250,0.736842,0.538462,0.384615,0.888889,0.583333,0.588235,0.764706,0.5625,0.647059,0.470588,0.7500,0.714286,0.800000,0.4375,0.454545,0.5625,0.571429,0.500000,0.888889,1.0,206
IF 5,0.611111,0.388889,0.538462,0.611111,0.529412,0.7500,0.444444,0.294118,0.500000,0.473684,0.333333,0.523810,0.75,0.583333,0.454545,0.500000,0.45,0.571429,0.384615,0.333333,0.600000,0.214286,0.444444,0.470588,0.750000,0.611111,0.5000,0.736842,0.307692,0.307692,0.833333,0.666667,0.588235,0.647059,0.5625,0.705882,0.529412,0.6250,0.500000,0.666667,0.5000,0.727273,0.6250,0.571429,0.583333,0.666667,1.0,206
IF 6,0.611111,0.444444,0.538462,0.555556,0.470588,0.6875,0.555556,0.470588,1.000000,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.5000,0.789474,0.538462,0.384615,0.777778,0.666667,0.529412,0.705882,0.6875,0.529412,0.588235,0.6875,0.500000,0.733333,0.3125,0.727273,0.6875,0.714286,0.416667,0.888889,1.0,168
IFT,0.611111,0.277778,0.538462,0.555556,0.529412,0.7500,0.388889,0.352941,0.428571,0.210526,0.333333,0.714286,0.75,0.500000,0.363636,0.416667,0.65,0.571429,0.461538,0.333333,0.466667,0.214286,0.611111,0.470588,0.583333,0.611111,0.5000,0.842105,0.615385,0.461538,0.777778,0.666667,0.529412,0.764706,0.7500,0.764706,0.647059,0.6250,0.500000,0.600000,0.3750,0.727273,0.5625,0.285714,0.583333,0.666667,1.0,206